project:
  type: website
  
from: markdown+emoji

website:
  title: "Fatih's Blog about R and Statistics"
  site-url: https://mfatihtuzen.netlify.app
  description: "Fatih's Blog about R and Statistics"
  navbar:
    right:
      - text: "About"
        href: about.html
      - icon: github
        href: https://github.com/MFatihTuzen
      - icon: linkedin
        href: https://www.linkedin.com/in/fatih-t-2b2a4328/
      - icon: rss
        href: index.xml
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; 2023, M. Fatih Tüzen"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual




