project:
  type: website

website:
  title: "Fatih's Blog about R and Statistics"
  site-url: https://mfatihtuzen.netlify.app
  navbar:
    right:
      - text: "About"
        href: about.html
      - icon: github
        href: https://github.com/MFatihTuzen
      - icon: linkedin
        href: https://www.linkedin.com/in/fatih-t-2b2a4328/
      - icon: rss
        href: blog.xml
format:
  html:
    theme: flatly
    css: styles.css

editor: visual


