project:
  type: website
  
from: markdown+emoji

website:
  title: "A Statistician's R Notebook"
  site-url: https://mfatihtuzen.netlify.app
  description: "Blog posts about R and Statistics"
  navbar:
    right:
      - text: "About"
        href: about.html
      - icon: github
        href: https://github.com/MFatihTuzen
      - icon: linkedin
        href: https://www.linkedin.com/in/dr-m-fatih-t-2b2a4328/
      - icon: rss
        href: index.xml
      - text: "BlogRoll"
        menu:
          - text: R-bloggers
            href: https://www.r-bloggers.com/
          - text: R-Studio Community
            href: https://community.rstudio.com/
          - text: R weekly
            href: https://rweekly.org/
          - text: Allison Horst
            href: https://allisonhorst.com/allison-horst
          - text: Github R Topics
            href: https://github.com/topics/r
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; 2023, M. Fatih Tüzen"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual




