{
  "hash": "f884ee8dbdc38956bba5e6fcf6cb7c72",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Handling Missing Data in R: A Comprehensive Guide\"\nauthor: M. Fatih Tüzen\ndate: today\ncategories: [R, Statistics, Data Analysis, Standard Deviation, Standard Error]\nexecute: \n  warning: false\n  message: false\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: true\n    code-tools: true\n    code-overflow: scroll\n    code-block-background: true\n---\n\n\n\n## Introduction\n\nMissing data is one of the most common challenges in data analysis and statistical modeling.\\\nWhether the data originates from surveys, administrative registers, or clinical trials, it is almost inevitable that some values are absent. Ignoring this issue or handling it incorrectly can seriously bias results, reduce statistical power, and ultimately lead to misleading conclusions.\n\nIn statistical notation, missing values are usually represented as **NA** (Not Available) in R.\\\nHowever, not all missing values are created equal: some are missing completely at random, while others may follow systematic patterns. Before deciding how to handle missingness, one must carefully investigate its causes and implications.\n\nIn this article, we will cover:\n\n-   The theoretical foundations of missing data mechanisms (MCAR, MAR, MNAR).\n-   How to detect and visualize missing values in R.\n-   Different strategies for handling missingness, from simple imputation to advanced multiple imputation techniques.\n-   A practical workflow using the **NHANES dataset**, widely used in health research, to demonstrate methods in R.\n-   Best practices, pitfalls, and recommendations for applied data science.\n\nWe will use several R packages throughout this tutorial:\n\n-   **tidyverse**: Data wrangling and visualization\n-   **naniar** and **VIM**: Tools for exploring and visualizing missing data\n-   **mice**: Multiple imputation by chained equations\n-   **missForest**: Random forest–based imputation for nonlinear data\n\nThis structured approach will help you not only handle missing data but also understand the reasoning behind each method, ensuring that your analyses remain robust and reliable.\n\n## NHANES Dataset\n\nIn this section, we will work with the **NHANES** dataset, which comes from the US National Health and Nutrition Examination Survey.\\\nThe dataset includes demographic, examination, and laboratory data collected from thousands of individuals.\\\nSince the full dataset is quite large, we will focus only on a subset of variables that are relevant for preprocessing examples.\n\nHere are the variables we will use:\n\n-   **ID**: Unique identifier for each participant\n-   **Age**: Age of the participant\n-   **Gender**: Biological sex (male or female)\n-   **BMI**: Body Mass Index\n-   **BPSysAve**: Average systolic blood pressure\n-   **Diabetes**: Whether the participant has been diagnosed with diabetes\n\nBefore diving into preprocessing, let’s take a quick look at the structure of these selected variables:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\nlibrary(dplyr)\n\ndata(\"NHANES\")\n\n# Select relevant variables\nnhanes_sub <- NHANES |> \n  select(ID, Age, Gender, BMI, BPSysAve, Diabetes)\n\nglimpse(nhanes_sub)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,000\nColumns: 6\n$ ID       <int> 51624, 51624, 51624, 51625, 51630, 51638, 51646, 51647, 51647…\n$ Age      <int> 34, 34, 34, 4, 49, 9, 8, 45, 45, 45, 66, 58, 54, 10, 58, 50, …\n$ Gender   <fct> male, male, male, male, female, male, male, female, female, f…\n$ BMI      <dbl> 32.22, 32.22, 32.22, 15.30, 30.57, 16.82, 20.64, 27.24, 27.24…\n$ BPSysAve <int> 113, 113, 113, NA, 112, 86, 107, 118, 118, 118, 111, 104, 134…\n$ Diabetes <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n```\n\n\n:::\n:::\n\n\n\n## Why Missingness Matters\n\nMissing data is not just an inconvenience — it can distort the statistical conclusions we draw from a dataset.\\\nThere are several critical reasons why handling missingness properly is essential:\n\n-   **Biased results**: If the missing values are not random, analyses may systematically misrepresent the population.\n-   **Reduced sample size**: Complete-case analysis (simply dropping missing rows) reduces data availability, weakening statistical power.\n-   **Model incompatibility**: Many modeling techniques in R (e.g., `lm()`, `glm()`) require complete data, and will automatically drop cases with missing values, sometimes silently.\n\n### A Short Case Example: BMI Missingness and Blood Pressure\n\nSuppose we want to explore how **Body Mass Index (BMI)** relates to **Systolic Blood Pressure (BPSysAve)**.\\\nHowever, BMI contains missing values. If we ignore them and only analyze complete cases, we may end up with biased conclusions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# How many missing in BMI?\nsum(is.na(nhanes_sub$BMI))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 366\n```\n\n\n:::\n\n```{.r .cell-code}\n# Complete-case dataset (dropping missing BMI)\nnhanes_complete <- nhanes_sub |> \n  filter(!is.na(BMI))\n\n# Compare sample sizes\nnrow(nhanes_sub)     # original sample size\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10000\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(nhanes_complete) # after dropping missing BMI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9634\n```\n\n\n:::\n:::\n\n\n\nWe see that a substantial portion of the data is dropped when we remove missing BMI values. This reduction not only decreases efficiency but can also **bias the estimates** if those missing values are not randomly distributed.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit regression with complete cases only\nmodel_complete <- lm(BPSysAve ~ BMI + Age + Gender, data = nhanes_complete)\nsummary(model_complete)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = BPSysAve ~ BMI + Age + Gender, data = nhanes_complete)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-56.281  -8.652  -0.955   7.560 102.790 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 90.016503   0.677618  132.84   <2e-16 ***\nBMI          0.328076   0.023228   14.12   <2e-16 ***\nAge          0.412758   0.008076   51.11   <2e-16 ***\nGendermale   4.346847   0.313476   13.87   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14.43 on 8483 degrees of freedom\n  (1147 observations deleted due to missingness)\nMultiple R-squared:  0.2969,\tAdjusted R-squared:  0.2966 \nF-statistic:  1194 on 3 and 8483 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n**Interpretation**:\n\n-   The model only uses complete cases, ignoring potentially informative missingness.\n-   If BMI is more often missing in certain subgroups (e.g., older adults or females), then the relationship estimated here does not represent the whole population.\n-   In later sections, we will see how different imputation strategies can mitigate this problem.\n\n## Missing Data Mechanisms\n\nOne of the most crucial aspects of handling missing data is to understand **why** the data are missing.\\\nThe mechanism behind missingness determines whether our chosen method will yield unbiased and efficient estimates.\n\n### Types of Missing Data Mechanisms\n\n-   **MCAR (Missing Completely At Random)**\\\n    The probability of a value being missing does not depend on either the observed or the unobserved data.\\\n    → Example: A lab machine randomly fails for some patients, regardless of their characteristics.\\\n    → Implication: Complete-case analysis is valid (though less efficient).\n\n-   **MAR (Missing At Random)**\\\n    The probability of missingness depends only on the **observed** data, not on the missing values themselves.\\\n    → Example: People with lower income are less likely to report their weight, but we observe income.\\\n    → Implication: Multiple imputation or likelihood-based methods can recover unbiased estimates.\n\n-   **MNAR (Missing Not At Random)**\\\n    The probability of missingness depends on the **unobserved** value itself.\\\n    → Example: People with higher BMI are less likely to report their weight.\\\n    → Implication: Strong assumptions or external information are needed; imputation under MAR will still be biased.\n\n### What each mechanism implies (with NHANES intuition)\n\n-   **MCAR** — e.g., random device failure that occasionally prevents recording `BMI`.\\\n    *Implication:* Complete-case analysis (dropping rows) is unbiased but wastes data.\n\n-   **MAR** — e.g., `BMI` missingness varies by observed **Age** or **Gender**.\\\n    *Implication:* Likelihood-based methods or **Multiple Imputation (MI)** are valid if those predictors are in the imputation model.\n\n-   **MNAR** — e.g., people with **very high BMI** systematically do not report it.\\\n    *Implication:* MAR-based methods still biased; requires **sensitivity analysis** or explicit MNAR models.\n\n### Quick NHANES checks that suggest a mechanism\n\nBelow we do two simple diagnostics on our working subset `nhanes_sub`\\\n(defined earlier as: `NHANES |> select(ID, Age, Gender, BMI, BPSysAve, Diabetes)`).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Packages we already use\nlibrary(dplyr)\nlibrary(knitr)\n\n# 1) Overall BMI missingness\nnhanes_sub |>\n  summarise(pct_missing_BMI = mean(is.na(BMI)) * 100) |>\n  mutate(pct_missing_BMI = round(pct_missing_BMI, 1)) |>\n  kable(caption = \"Overall BMI missingness (%)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Overall BMI missingness (%)\n\n| pct_missing_BMI|\n|---------------:|\n|             3.7|\n\n\n:::\n\n```{.r .cell-code}\n# 2) Does BMI missingness vary by observed variables? (MAR hint)\n#    - By Gender\nby_gender <- nhanes_sub |>\n  group_by(Gender) |>\n  summarise(pct_miss_BMI = mean(is.na(BMI)) * 100,\n            n = n(), .groups = \"drop\") |>\n  mutate(pct_miss_BMI = round(pct_miss_BMI, 1))\n\n#    - By Age groups (bins)\nby_age <- nhanes_sub |>\n  mutate(AgeBand = cut(Age, breaks = c(0, 30, 45, 60, Inf),\n                       labels = c(\"<=30\", \"31–45\", \"46–60\", \"60+\"),\n                       right = FALSE)) |>\n  group_by(AgeBand) |>\n  summarise(pct_miss_BMI = mean(is.na(BMI)) * 100,\n            n = n(), .groups = \"drop\") |>\n  mutate(pct_miss_BMI = round(pct_miss_BMI, 1))\n\n# Show summaries nicely\nkable(by_gender, caption = \"BMI missingness by Gender (%)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: BMI missingness by Gender (%)\n\n|Gender | pct_miss_BMI|    n|\n|:------|------------:|----:|\n|female |          3.6| 5020|\n|male   |          3.8| 4980|\n\n\n:::\n\n```{.r .cell-code}\nkable(by_age,    caption = \"BMI missingness by Age band (%)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: BMI missingness by Age band (%)\n\n|AgeBand | pct_miss_BMI|    n|\n|:-------|------------:|----:|\n|<=30    |          7.6| 4121|\n|31–45   |          0.5| 2049|\n|46–60   |          0.6| 1991|\n|60+     |          1.7| 1839|\n\n\n:::\n:::\n\n\n\n**Interpretation:**\n\n-   If `pct_miss_BMI` is **similar across groups**, MCAR is more plausible.\n\n-   If missingness **changes with Age or Gender**, **MAR** is more plausible (we must include those predictors in imputation).\n\n-   These are *indicators*, not proofs; true **MNAR** needs external info or sensitivity analyses.\n\n**Which methods are valid under which mechanism?**\n\n| Mechanism | Example (NHANES context)                             | Valid methods                                             | Notes                                    |\n|---------------|--------------------|----------------------|---------------|\n| **MCAR**  | Random loss of `BMI` records                         | Complete-case, single imputation, MI                      | Unbiased but may waste data              |\n| **MAR**   | `BMI` missingness varies by observed `Age`, `Gender` | **Multiple Imputation (MICE)**, likelihood/EM, missForest | Include strong predictors of missingness |\n| **MNAR**  | People with very high `BMI` hide it                  | Sensitivity analysis, selection/pattern-mixture models    | MAR-based MI alone is biased             |\n\n::: callout-note\n### Optional: Little’s MCAR Test\n\nLittle’s MCAR test is a statistical procedure used to examine whether data are **Missing Completely at Random (MCAR)**.\n\n⚠️ However, this test comes with important caveats:\\\n- It can be overly sensitive in **large samples**, flagging trivial deviations.\\\n- In **small samples**, its power is often too low to detect meaningful departures from MCAR.\n\nBecause of these limitations, it should be treated only as a **supporting tool** rather than a definitive test when diagnosing missingness mechanisms.\n:::\n\n## Detecting Missing Data\n\nBefore applying any imputation or modeling technique, it is essential to explore the **extent and structure of missingness** in the dataset. The `nhanes_sub` data frame, derived from the NHANES dataset, will be used for illustration.\n\n### Simple Counts and Summaries\n\nThe first step is to quantify how many values are missing per variable.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count missing values for each variable\nnhanes_sub %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n     ID   Age Gender   BMI BPSysAve Diabetes\n  <int> <int>  <int> <int>    <int>    <int>\n1     0     0      0   366     1449      142\n```\n\n\n:::\n:::\n\n\n\nThe output shows the number of missing values in each column, making it easy to spot problematic variables. Another quick check is to identify how many **complete vs. incomplete cases** exist:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(complete.cases(nhanes_sub))       # number of complete rows\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8482\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(!complete.cases(nhanes_sub))      # number of incomplete rows\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1518\n```\n\n\n:::\n:::\n\n\n\nThis gives us an idea of the proportion of observations that would be lost if we opted for **listwise deletion**.\n\n### Visualizing Missingness\n\nTextual summaries are informative, but missing data often has **patterns** that are better revealed visually. Several R packages support this task:\n\n#### `naniar`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(naniar)\nlibrary(ggplot2)\n\n# Visualize missing values by variable\ngg_miss_var(nhanes_sub, show_pct = TRUE) +\n  labs(title = \"Missing Values by Variable in NHANES Subset\",\n       x = \"Variables\",\n       y = \"Proportion of Missing Values\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n-   Each bar corresponds to a variable.\n\n-   The **height of the bar** shows how many observations are missing for that variable.\n\n-   With `show_pct = TRUE`, the proportion of missing values is also displayed, making it easier to compare across variables.\n\n-   Variables with tall bars clearly have higher missingness (e.g., BMI or blood pressure variables often stand out in this dataset).\n\n#### `VIM`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(VIM)\n\naggr(nhanes_sub, numbers = TRUE, prop = FALSE, sortVar = TRUE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Variables sorted by number of missings: \n Variable Count\n BPSysAve  1449\n      BMI   366\n Diabetes   142\n       ID     0\n      Age     0\n   Gender     0\n```\n\n\n:::\n:::\n\n\n\nThis aggregated visualization shows the proportion of missing values per variable and the combinations of missingness across variables.\n\n#### `visdat`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(visdat)\n\nvis_dat(nhanes_sub)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\nThis function displays the data type of each variable and overlays missingness, helping to identify whether missing values cluster in certain variable types (e.g., numeric vs. categorical).\n\n### Interpreting the Patterns\n\n-   **Random scatter of missing values** across rows/columns may indicate **MCAR** (though formal testing is required).\n-   **Systematic patterns** (e.g., older participants more likely to have missing BMI) hint at **MAR**.\n-   **Blocks of missingness** (entire variables missing for subgroups) may suggest **MNAR** or structural missingness.\n\n## Handling Missing Data — Methods\n\nIn this section we review the main families of methods, show **when** each is appropriate, and demonstrate them on `nhanes_sub`. We will explicitly call out the **trade-offs** so readers can choose deliberately—not by habit.\n\n------------------------------------------------------------------------\n\n### Deletion\n\n**Listwise deletion (complete-case)** removes any row that contains *at least one* missing value.\\\n**Pairwise deletion** uses all available pairs to compute correlations/covariances, which can later lead to **non–positive-definite** covariance matrices and failures in modeling.\n\n-   **Pros** - Simple; widely implemented by default (often silently). - Unbiased *only* under **MCAR**.\n\n-   **Cons** - Wastes data; reduces power. - Biased under **MAR/MNAR**; can change the sample composition.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# How many rows would we lose if we required complete cases for these variables?\nn_total <- nrow(nhanes_sub)\nn_cc    <- nhanes_sub |> stats::complete.cases() |> sum()\n\ncbind(\n  total_rows    = n_total,\n  complete_cases= n_cc,\n  lost_rows     = n_total - n_cc,\n  lost_pct      = round((n_total - n_cc) / n_total * 100, 1)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     total_rows complete_cases lost_rows lost_pct\n[1,]      10000           8482      1518     15.2\n```\n\n\n:::\n:::\n\n\n\n**Interpretation:** If the lost percentage is non-trivial (e.g., \\>5–10%), listwise deletion both **shrinks power** and **risks bias** unless MCAR truly holds. Pairwise deletion is **not recommended** for modeling because it can yield inconsistent covariance structures.\n\n### Simple Imputation\n\n**Idea.** Fill missing values with a single plausible value (one pass). Fast and convenient, but it **underestimates uncertainty** (standard errors too small) and can **distort distributions**.\n\n**Typical choices**\n\n-   **Mean/Median/Mode** (baselines; median is more robust to skew)\n\n-   **k-Nearest Neighbors (kNN)** (borrows information from similar rows)\n\n-   **Hot-deck** (donor-based; similar spirit to kNN)\n\n#### Median (numeric) + Mode (categorical) baselines\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2025)\n\n# Create a median-imputed BMI for illustration (only if BMI is missing)\nnh_med <- nhanes_sub |>\n  mutate(\n    BMI_med = ifelse(is.na(BMI), stats::median(BMI, na.rm = TRUE), BMI)\n  )\n\n# Compare how many BMI were imputed\nsum(is.na(nhanes_sub$BMI))           # original missing BMI count\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 366\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(nh_med$BMI_med))           # should be 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n**Distribution distortion (variance shrinkage).**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Compare BMI distribution: complete-case vs median-imputed\np_cc  <- nhanes_sub |>\n  filter(!is.na(BMI)) |>\n  ggplot(aes(x = BMI)) +\n  geom_density() +\n  labs(title = \"BMI density — complete cases\")\n\np_med <- nh_med |>\n  ggplot(aes(x = BMI_med)) +\n  geom_density() +\n  labs(title = \"BMI density — median-imputed\")\n\np_cc; p_med\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n:::\n\n\n\n**Interpretation:** Median imputation **spikes** the distribution around the median and **reduces variance**. This can attenuate real relationships that depend on dispersion.\n\n#### kNN (donor-based) imputation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# kNN imputation with VIM::kNN (works on data frames; chooses donors by similarity)\nlibrary(VIM)\n\n# We impute only BMI here; set k=5 as a reasonable starting point.\nnh_knn <- nhanes_sub |>\n  select(Age, Gender, BMI, BPSysAve, Diabetes) |>\n  VIM::kNN(k = 5, imp_var = FALSE)  # imp_var=FALSE avoids extra *_imp columns\n\n# Check imputation effect\nsum(is.na(nhanes_sub$BMI))   # original missing BMI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 366\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(nh_knn$BMI))       # after kNN (should be 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n**Interpretation:** kNN preserves local structure better than mean/median, but it is still **single imputation** → uncertainty is **not** propagated. Choice of **k** and included predictors matters.\n\n> **Rule of thumb.** Simple methods are acceptable for quick EDA or as baselines. For principled inference under MAR, prefer **Multiple Imputation**.\n\n### Advanced Methods\n\n#### Multiple Imputation with `mice`\n\nSo far, we have seen that missing values exist in several variables of our dataset. A common and powerful approach to handle missingness is **Multiple Imputation by Chained Equations (MICE)**. The `mice` package in R is widely used for this purpose. The idea is simple:\n\n-   Instead of filling in missing values once, MICE creates **multiple complete datasets** by imputing values several times.\n-   Each dataset is then analyzed separately.\n-   Finally, results are pooled together to account for the variability introduced by missingness.\n\nLet’s try this approach on our subset of the `NHANES` data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mice)\n\n# Create imputations\nimp <- mice(nhanes_sub, m = 3, seed = 123)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n iter imp variable\n  1   1  BMI  BPSysAve  Diabetes\n  1   2  BMI  BPSysAve  Diabetes\n  1   3  BMI  BPSysAve  Diabetes\n  2   1  BMI  BPSysAve  Diabetes\n  2   2  BMI  BPSysAve  Diabetes\n  2   3  BMI  BPSysAve  Diabetes\n  3   1  BMI  BPSysAve  Diabetes\n  3   2  BMI  BPSysAve  Diabetes\n  3   3  BMI  BPSysAve  Diabetes\n  4   1  BMI  BPSysAve  Diabetes\n  4   2  BMI  BPSysAve  Diabetes\n  4   3  BMI  BPSysAve  Diabetes\n  5   1  BMI  BPSysAve  Diabetes\n  5   2  BMI  BPSysAve  Diabetes\n  5   3  BMI  BPSysAve  Diabetes\n```\n\n\n:::\n\n```{.r .cell-code}\n# Look at a summary\nimp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nClass: mids\nNumber of multiple imputations:  3 \nImputation methods:\n      ID      Age   Gender      BMI BPSysAve Diabetes \n      \"\"       \"\"       \"\"    \"pmm\"    \"pmm\" \"logreg\" \nPredictorMatrix:\n         ID Age Gender BMI BPSysAve Diabetes\nID        0   1      1   1        1        1\nAge       1   0      1   1        1        1\nGender    1   1      0   1        1        1\nBMI       1   1      1   0        1        1\nBPSysAve  1   1      1   1        0        1\nDiabetes  1   1      1   1        1        0\n```\n\n\n:::\n:::\n\n\n\nThe output shows:\n\n-   `m = 3`: number of imputed datasets created.\n\n-   For each variable with missingness, the method used for imputation.\n\n-   How many iterations were performed in the algorithm.\n\nWe can take a quick look at the imputed values:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Inspect first few imputations for BMI\nhead(imp$imp$BMI)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1     2     3\n61  43.00 17.70 12.90\n161 16.70 13.50 18.59\n210 16.28 24.00 23.10\n309 24.00 37.32 26.20\n310 24.00 28.55 26.30\n320 25.10 32.25 29.20\n```\n\n\n:::\n:::\n\n\n\nThis shows different plausible values for missing BMI observations across the three imputed datasets. Each dataset gives slightly different results, which is expected and important for reflecting uncertainty.\n\nOnce we have these imputations, we can **complete the dataset**:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract the first imputed dataset\nnhanes_completed <- complete(imp, 1)\n\nhead(nhanes_completed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     ID Age Gender   BMI BPSysAve Diabetes\n1 51624  34   male 32.22      113       No\n2 51624  34   male 32.22      113       No\n3 51624  34   male 32.22      113       No\n4 51625   4   male 15.30       92       No\n5 51630  49 female 30.57      112       No\n6 51638   9   male 16.82       86       No\n```\n\n\n:::\n:::\n\n\n\nNow we have a complete dataset with no missing values. In practice, we would analyze all imputed datasets and then combine results using Rubin’s rules, but the key takeaway here is:\n\n-   `mice()` provides multiple versions of the data,\n\n-   imputations are based on relationships among variables,\n\n-   and the method preserves uncertainty rather than hiding it.\n\n::: callout-note\n### MICE Essentials: Key Arguments\n\n-   **method**: Specifies the imputation model for each variable.\n\n    -   `pmm`: predictive mean matching (continuous variables)\n    -   `logreg`: logistic regression (binary)\n    -   `polyreg`: multinomial regression (nominal categorical)\n    -   `polr`: proportional odds model (ordered categorical)\n\n    *Rule of thumb*: If a factor has \\>2 levels, prefer `polyreg` (nominal) or `polr` (ordered) instead of `logreg`. Always check the actual levels of variables such as `Gender` or `Diabetes` in your data before setting methods.\n\n-   **predictorMatrix**: Controls which variables are used to predict others.\n\n    -   Rows = target variables (to be imputed)\n    -   Columns = predictor variables\n\n-   **m**: Number of multiple imputations to generate (commonly 5–20).\n\n    -   More imputations recommended for high missingness.\n\n-   **maxit**: Number of iterations of the chained equations (often 5–10).\n\n-   **seed**: Random seed for reproducibility.\n\n    -   Always set when writing tutorials or reports.\n:::\n\n#### Multiple Imputation with missForest\n\nThe **missForest** package provides a non-parametric imputation method based on random forests.\\\nUnlike `mice`, which generates multiple imputations, `missForest` creates a **single completed dataset** by iteratively predicting missing values using random forest models. It works well with both continuous and categorical variables and can capture nonlinear relationships.\n\nWe will use the same `nhanes_sub` dataset as before:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(missForest)\n\n# Start from the existing subset:\n# nhanes_sub <- NHANES |> select(ID, Age, Gender, BMI, BPSysAve, Diabetes)\n\n# 1) Keep only model-relevant columns (drop pure identifier)\n# 2) Convert character variables to factors (missForest expects factors, not raw character)\n# 3) Coerce to base data.frame to avoid tibble-related method dispatch issues\nmf_input <- nhanes_sub |>\n  select(Age, Gender, BMI, BPSysAve, Diabetes) |>\n  mutate(across(where(is.character), as.factor)) |>\n  as.data.frame()\n\nset.seed(123)\nmf_fit <- missForest(\n  mf_input,\n  ntree   = 200,    # more trees -> stabler imputations\n  maxiter = 5,      # outer iterations (default 10; 5 is fine for demo)\n  verbose = FALSE\n)\n\n# Completed data and OOB error\nmf_imputed <- mf_fit$ximp\nmf_oob     <- mf_fit$OOBerror\n\n# Quick checks\nsum(is.na(mf_input$BMI))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 366\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(mf_imputed$BMI))   # should go to 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nmf_oob\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     NRMSE        PFC \n0.17890307 0.02667884 \n```\n\n\n:::\n:::\n\n\n\nThe function returns a list with two key elements:\n\n-   `ximp`: the completed dataset after imputation.\n\n-   `OOBerror`: the estimated imputation error (normalized root mean squared error for continuous variables and proportion of falsely classified entries for categorical variables).\n\n**Interpretation:**\n\n-   The **completed dataset** (`ximp`) replaces all missing values with imputed estimates.\n\n-   **NRMSE (Normalized Root Mean Squared Error):** `0.1789`\n\n    -    This value reflects the imputation error for continuous variables (e.g., `Age`, `BMI`, `BPSysAve`).\n    -   Since it is normalized, values closer to **0** indicate better accuracy. Here, an error of \\~0.18 suggests that the imputed values are quite close to the true (non-missing) values.\n\n-   **PFC (Proportion of Falsely Classified):** `0.0267`\n\n    -    This metric evaluates categorical variables (e.g., `Gender`, `Diabetes`).\n    -   A value of \\~0.027 means only about **2.7% of categorical imputations were misclassified**, which is a strong performance.\n\n✅ **Interpretation:**\\\nThe results indicate that `missForest` produced high-quality imputations: continuous variables are imputed with relatively low error, and categorical variables with very low misclassification. In practical terms, this means the dataset after imputation is reliable and close to the original data distribution.\n\n**Pros and Cons of `missForest`**\n\n**Advantages:**\n\n-   Handles mixed data types (continuous + categorical).\n-   Captures nonlinearities and complex interactions.\n-   No need to specify an explicit imputation model.\n\n**Limitations:**\n\n-   Produces only a **single imputed dataset**, so uncertainty is not directly quantified (unlike `mice`).\n-   Computationally more expensive for very large datasets.\n\n## Single vs. Multiple Imputation\n\nOne critical distinction in handling missing data is **single imputation** vs. **multiple imputation (MI)**.\n\n-    **Single imputation** (mean, median, regression, etc.) fills each missing value once. While simple, it **ignores uncertainty**, treating imputed values as if they were observed.\n\n-   **Multiple imputation** generates **several plausible versions of the dataset** (e.g., 5–10). Each dataset is analyzed separately, and results are then combined (pooled). This approach accounts for **variability due to missingness** and produces more reliable inferences.\n\nLet’s illustrate with our `nhanes_sub` dataset:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Complete-case analysis (ignores missing data)\nlm_cc <- lm(BMI ~ Age + Gender + BPSysAve + Diabetes,\n            data = nhanes_sub, na.action = na.omit)\n\n# Single imputation (mean imputation for BMI)\nnhanes_single <- nhanes_sub |> \n  mutate(BMI = ifelse(is.na(BMI), mean(BMI, na.rm = TRUE), BMI))\n\nlm_si <- lm(BMI ~ Age + Gender + BPSysAve + Diabetes,\n            data = nhanes_single)\n\n# Multiple imputation with mice\nimp <- mice(nhanes_sub, m = 5, method = \"pmm\", seed = 123)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n iter imp variable\n  1   1  BMI  BPSysAve  Diabetes\n  1   2  BMI  BPSysAve  Diabetes\n  1   3  BMI  BPSysAve  Diabetes\n  1   4  BMI  BPSysAve  Diabetes\n  1   5  BMI  BPSysAve  Diabetes\n  2   1  BMI  BPSysAve  Diabetes\n  2   2  BMI  BPSysAve  Diabetes\n  2   3  BMI  BPSysAve  Diabetes\n  2   4  BMI  BPSysAve  Diabetes\n  2   5  BMI  BPSysAve  Diabetes\n  3   1  BMI  BPSysAve  Diabetes\n  3   2  BMI  BPSysAve  Diabetes\n  3   3  BMI  BPSysAve  Diabetes\n  3   4  BMI  BPSysAve  Diabetes\n  3   5  BMI  BPSysAve  Diabetes\n  4   1  BMI  BPSysAve  Diabetes\n  4   2  BMI  BPSysAve  Diabetes\n  4   3  BMI  BPSysAve  Diabetes\n  4   4  BMI  BPSysAve  Diabetes\n  4   5  BMI  BPSysAve  Diabetes\n  5   1  BMI  BPSysAve  Diabetes\n  5   2  BMI  BPSysAve  Diabetes\n  5   3  BMI  BPSysAve  Diabetes\n  5   4  BMI  BPSysAve  Diabetes\n  5   5  BMI  BPSysAve  Diabetes\n```\n\n\n:::\n\n```{.r .cell-code}\nlm_mi <- with(imp, lm(BMI ~ Age + Gender + BPSysAve + Diabetes))\npooled <- pool(lm_mi)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = BMI ~ Age + Gender + BPSysAve + Diabetes, data = nhanes_sub, \n    na.action = na.omit)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-18.771  -4.640  -1.053   3.553  53.003 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17.488597   0.513225  34.076   <2e-16 ***\nAge          0.047930   0.004273  11.217   <2e-16 ***\nGendermale  -0.278756   0.144799  -1.925   0.0542 .  \nBPSysAve     0.067504   0.004903  13.767   <2e-16 ***\nDiabetesYes  3.789606   0.265240  14.287   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.588 on 8477 degrees of freedom\n  (1518 observations deleted due to missingness)\nMultiple R-squared:  0.1136,\tAdjusted R-squared:  0.1132 \nF-statistic: 271.5 on 4 and 8477 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(lm_si)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = BMI ~ Age + Gender + BPSysAve + Diabetes, data = nhanes_single)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-18.657  -4.634  -1.029   3.533  53.004 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17.600406   0.508667  34.601   <2e-16 ***\nAge          0.047159   0.004237  11.129   <2e-16 ***\nGendermale  -0.287221   0.143820  -1.997   0.0458 *  \nBPSysAve     0.066791   0.004858  13.748   <2e-16 ***\nDiabetesYes  3.725941   0.262781  14.179   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.57 on 8541 degrees of freedom\n  (1454 observations deleted due to missingness)\nMultiple R-squared:  0.1118,\tAdjusted R-squared:  0.1114 \nF-statistic: 268.8 on 4 and 8541 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(pooled)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         term    estimate   std.error statistic       df       p.value\n1 (Intercept) 14.66559186 0.487686304 30.071773 1253.210 5.075329e-150\n2         Age  0.10367759 0.003748806 27.656164 3916.798 6.073157e-154\n3  Gendermale -0.30521870 0.134707691 -2.265785 3727.382  2.352165e-02\n4    BPSysAve  0.06754332 0.004761820 14.184349 1160.000  3.121286e-42\n5 DiabetesYes  3.23549109 0.260299313 12.429887 8866.664  3.529334e-35\n```\n\n\n:::\n:::\n\n\n\nWe applied three different approaches to handle missing BMI values in the `nhanes_sub` dataset, modeling **BMI \\~ Age + Gender + BPSysAve + Diabetes**. Here is what we found:\n\n**1. Complete-Case Analysis (CCA)**\n\n-    **What we did:** We dropped all observations with missing values (`na.omit`).\n\n-   **Result:**\n\n    -    **Coefficients:** Age (0.048), BPSysAve (0.068), DiabetesYes (+3.79), Gender slightly negative.\n\n    -   **Standard errors:** Relatively large because \\~1500 observations were discarded.\n\n    -   **R²:** 0.114 — fairly low.\n\n-    **Takeaway:** CCA wastes data and may bias estimates if missingness is not MCAR (Missing Completely at Random).\n\n**2. Single Imputation (Mean Substitution for BMI)**\n\n-    **What we did:** Replaced missing BMI values with the mean BMI.\n\n-   **Result:**\n\n    -   **Coefficients:** Very close to CCA (Age 0.047, BPSysAve 0.067, DiabetesYes +3.73).\n\n    -   **Gender** effect became just significant (*p* = 0.045).\n\n    -   **Residual SE** decreased slightly (6.57).\n\n-    **Takeaway:** Looks “better” because all observations are retained, but this approach **ignores imputation uncertainty** and artificially stabilizes estimates. Standard errors are underestimated, leading to overconfidence.\n\n**3. Multiple Imputation (MI with `mice`, m = 5, method = \"pmm\")**\n\n-    **What we did:** Generated 5 imputed datasets using Predictive Mean Matching (PMM), fit the same model in each, and pooled results.\n\n-   **Result:**\n\n    -   **Coefficients:** Age effect doubled (0.104), intercept dropped (14.7 vs. \\~17.5), Diabetes effect slightly smaller (+3.24), Gender effect remained modest but significant (*p* = 0.023).\n\n    -   **Standard errors:** Properly adjusted upwards — reflecting real uncertainty in imputed BMI values.\n\n    -   **Inference:** Despite differences in point estimates, the conclusions are more **statistically honest**.\n\n-    **Takeaway:** MI balances efficiency (uses all data) and validity (acknowledges missingness uncertainty).\n\n**🔑 Overall Comparison**\n\n| Method                   | Keeps All Data        | Coefficients Similar?         | SE Adjusted for Uncertainty? | Main Issue               |\n|--------------------------|-----------------------|-------------------------------|------------------------------|--------------------------|\n| Complete Case (CCA)      | ❌ (\\~1500 rows lost) | Yes, but less precise         | ✅ (but biased if MAR/MNAR)  | Data loss, possible bias |\n| Single Imputation (SI)   | ✅                    | Similar to CCA                | ❌ Underestimated            | Overconfident inference  |\n| Multiple Imputation (MI) | ✅                    | Somewhat different (esp. Age) | ✅ Properly adjusted         | More computation needed  |\n\n**Interpretation:**\n\n-    **Complete-case** drops too much data and risks bias.\n\n-   **Single imputation** keeps the data but gives *too much confidence* in results.\n\n-   **Multiple imputation** changes some coefficients (notably Age) and reports more realistic uncertaint\n\n👉 **Lesson:** If your goal is valid inference, especially in epidemiological or social science settings, **multiple imputation is the gold standard**.\n\n## Comparison of Common Imputation Methods\n\n| Method                                          | Description                                                        | Advantages                                        | Disadvantages                                    |\n|-------------------------------------------------|--------------------------------------------------------------------|---------------------------------------------------|--------------------------------------------------|\n| Listwise Deletion                               | Removes all observations containing missing values                 | Very simple, quick to implement                   | Substantial data loss, potential bias            |\n| Mean / Median / Mode                            | Replaces missing values with a fixed statistic                     | Easy to apply, preserves sample size              | Reduces variance, distorts relationships         |\n| LOCF (Last Observation Carried Forward)         | Uses the last available value (mainly time series)                 | Useful in longitudinal data, preserves continuity | Ignores trends, underestimates variability       |\n| Linear Interpolation                            | Estimates missing values by connecting known data points           | Maintains trends, intuitive                       | Fails with sudden changes or nonlinear patterns  |\n| KNN Imputation                                  | Predicts missing values using nearest neighbors                    | Preserves multivariate structure, flexible        | Computationally expensive, sensitive to k choice |\n| MICE (Multiple Imputation by Chained Equations) | Iterative regression-based multiple imputation                     | Accounts for uncertainty, widely used in research | Time-consuming, requires expertise               |\n| missForest                                      | Uses Random Forest to impute missing values                        | Handles nonlinearities and interactions           | Black-box method, computationally intensive      |\n| EM Algorithm                                    | Iterative expectation-maximization for likelihood-based estimation | Statistically principled, robust in theory        | Requires strong assumptions, advanced knowledge  |\n\nNo single imputation method is universally optimal—each comes with trade-offs between simplicity, accuracy, and interpretability. For instance, **listwise deletion** is tempting for its ease but can heavily bias results if missingness is not random. Simple **mean or median imputation** keeps the dataset intact but artificially reduces variability and masks true correlations. More advanced techniques such as **MICE, missForest, and EM** provide statistically sound imputations that preserve uncertainty and relationships, but they demand more computational resources and methodological expertise.\n\nIn practice:\n\n-   **Exploratory analysis** often starts with simple methods (e.g., median replacement) to get a sense of the data.\n\n-   **Time series data** may rely on **LOCF or interpolation**.\n\n-    **Complex survey or clinical datasets** typically benefit from advanced approaches like **MICE** or **missForest**, which better respect the multivariate nature of the data.\n\nUltimately, the choice depends on the **data structure, missingness mechanism (MCAR, MAR, MNAR), and analytical goals**.\n\n## Conclusion\n\nThere is **no one-size-fits-all** solution for missing data. The right approach depends on your **goal (prediction vs. inference)**, the **missingness mechanism (MCAR/MAR/MNAR)**, your **data structure** (cross-sectional vs. longitudinal), and **practical constraints** (time, compute, expertise).\n\n### What our NHANES walkthrough showed\n\n-   **Complete-case analysis** is simple but wastes data and can bias results unless MCAR is plausible.\n-   **Single imputation** (mean/median, kNN, missForest run once) keeps all rows but **underestimates uncertainty**, yielding overconfident inferences.\n-   **Multiple imputation (MICE)** typically strikes the best balance for **inference under MAR**: it preserves multivariate structure and **propagates uncertainty** (via pooling), producing more honest standard errors and CIs.\n-   **Nonparametric imputers** like **missForest** are strong for **predictive accuracy** on complex, nonlinear structure, but they do **not** capture imputation uncertainty by themselves.\n\n### Practical guidance (decision-oriented)\n\n-   **If your main task is prediction** and interpretability is secondary → a good single-imputation engine (e.g., **missForest**) can be effective, with careful validation.\n-   **If your main task is inference** (effect sizes, CIs, p-values) and **MAR is reasonable** → prefer **MICE**; include strong predictors of both the outcome and missingness; check diagnostics.\n-   **If you suspect MNAR** → acknowledge this explicitly and consider **sensitivity analyses** (pattern-mixture/selection models) rather than assuming MAR.\n\n### Reporting checklist (make your analysis reproducible & credible)\n\n-   \\% missing **by variable** and **by key subgroups** (e.g., Age, Gender).\n-   Your **assumed mechanism** (MCAR/MAR/MNAR) and why it’s plausible.\n-   The **method(s)** used (e.g., MICE with `pmm`, `m`, `maxit`, `predictorMatrix`; or missForest with `ntree`, `maxiter`).\n-   **Diagnostics** (trace/density/strip plots for MICE; OOB error for missForest).\n-   For MI: **pooled estimates** with standard errors/intervals; clarify how pooling was performed.\n-   **Limitations** (e.g., potential MNAR, model misspecification, small-sample caveats).\n\n::: callout-tip\n**Rule of thumb.** Use simple methods for quick EDA; use **MICE** for publication-grade inference under MAR; use **missForest** when you primarily need strong **predictive performance** on mixed/complex data.\n:::\n\n### Common pitfalls to avoid\n\n-   Treating imputed values as if they were observed “truth” (single imputation + significance testing).\n-   Imputing the **outcome** itself (generally avoid; let it *inform* predictor imputations instead).\n-   Ignoring **leakage**: fit imputers **within** resampling folds/splits, not on the full data.\n-   Omitting key covariates that explain missingness (weakens the MAR assumption and the imputer).\n\n### Where to go next\n\n-   **Leakage-free pipelines** with `tidymodels::recipes` (train/test split done right).\n-   **Sensitivity analyses** for MNAR.\n-   **Robustness checks** (alternative imputation models, different `m`, predictor sets).\n\n**Bottom line:** Choose methods intentionally, **justify assumptions**, show diagnostics, and **report pooled results** when using MI. Good missing-data practice is less about one magic function and more about transparent, principled workflow.\n\n## References\n\n-    Allison, P. D. (2001). *Missing Data*. Sage Publications.\n\n-   Enders, C. K. (2010). *Applied Missing Data Analysis*. The Guilford Press.\n\n-   Little, R. J. A., & Rubin, D. B. (2002). *Statistical Analysis with Missing Data* (2nd ed.). Wiley.\n\n-   van Buuren, S. (2018). *Flexible Imputation of Missing Data* (2nd ed.). Chapman & Hall/CRC.\n\n-   Stekhoven, D. J., & Bühlmann, P. (2012). “MissForest—Nonparametric Missing Value Imputation for Mixed-Type Data.” *Bioinformatics*, 28(1), 112–118. https://doi.org/10.1093/bioinformatics/btr597\n\n-   Rubin, D. B. (1987). *Multiple Imputation for Nonresponse in Surveys*. Wiley.\n\n-   Schafer, J. L. (1997). *Analysis of Incomplete Multivariate Data*. Chapman & Hall/CRC.\n\n-   R Documentation: [`mice` package](https://cran.r-project.org/package=mice)\n\n-   R Documentation: [`missForest` package](https://cran.r-project.org/package=missForest)\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}