{
  "hash": "20a76ab5138726750f7256396edbce6f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data Normalization in R: When, Why, and How to Scale Your Data Correctly\"\nauthor: \"M. Fatih Tüzen\"\ndate: \"2026-01-02\"\ncategories:\n  - Data Preprocessing\n  - R Programming\n  - Data Science\n  - Machine Learning\nformat:\n  html:\n    toc: true\n    toc-depth: 4\n    number-sections: true\n    code-tools: true\n    code-overflow: scroll\n    code-block-background: true\n  pdf:\n    toc: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n![](normalization.png){fig-align=\"center\" width=\"491\"}\n\n## Introduction\n\nThis article is part of a broader series on **data preprocessing in R**. In earlier posts, we focused on two problems that quietly ruin analyses long before modeling begins: **missing data** and **outliers**. Both topics shared a common theme: preprocessing choices are not cosmetic; they change what the model is allowed to learn. In this installment, we move to the next decision point in the same pipeline: **normalization (scaling)**—often treated as “just a quick step,” but in practice a decisive modeling choice.\n\n> **Related posts in this preprocessing series**\n>\n> -   *Handling Missing Data in R: A Comprehensive Guide*\\\n>     <https://medium.com/r-evolution/handling-missing-data-in-r-a-comprehensive-guide-eca195eaead3>\n>\n> -   *Outliers in Data Analysis: Detecting Extreme Values Before Modeling in R*\\\n>     <https://medium.com/r-evolution/outliers-in-data-analysis-detecting-extreme-values-before-modeling-in-r-with-i%CC%87stanbul-airbnb-data-3b37e9ee989e>\n\nNormalization (or more broadly, scaling) is frequently presented as a minor technical adjustment—something to apply quickly and forget. In practice, scaling is not a technical detail but a modeling decision. When the same dataset is processed using different scaling strategies, the behavior of many models changes substantially. Distances, similarity measures, penalty terms, and optimization paths are all affected. As a result, the nearest neighbors selected by KNN, the clusters formed by K-means, the principal components identified by PCA, and even the coefficients chosen by Ridge or Lasso regression can differ. Scaling does not merely “prepare” the data; it actively shapes how a model interprets importance and structure.\n\nMore importantly, scaling is not universally beneficial. Applied in the wrong context, it can degrade model performance or—worse—introduce subtle forms of **data leakage** that contaminate evaluation. A common example is learning scaling parameters (such as means and standard deviations) from the entire dataset before splitting into training and test sets. This procedure allows information from the test distribution to leak into the training process, producing performance estimates that cannot be trusted. In such cases, the issue is not the scaling method itself, but **when and how** it is applied. Knowing how to call `scale()` in R is trivial; understanding what to scale, when to scale it, and why is not.\n\nIn this article, normalization is treated as an integral part of the modeling strategy rather than a routine preprocessing step. We will address, step by step, the following questions:\n\n-   Why is normalization necessary?\n-   Should it always be applied?\n-   At what stage should it be performed—before or after the train–test split?\n-   Which scaling methods are commonly used, and in which contexts do they make sense?\n-   Should different data types be treated differently?\n-   Is scaling appropriate for all variables, including the target variable?\n\nBy combining conceptual discussion with practical R implementations, this guide aims to provide clear and principled answers to each of these questions.\n\n## Normalization vs. Standardization: Clearing Up the Terminology\n\nIn both academic writing and everyday practice, the terms *normalization* and *standardization* are frequently used interchangeably. This loose usage is one of the main sources of confusion in data preprocessing. In reality, these terms refer to **different scaling strategies**, each with distinct assumptions, effects, and use cases. Before discussing when and how scaling should be applied, it is therefore essential to clarify what is actually meant by each approach.\n\n**Standardization**, often referred to as *z-score scaling*, rescales a variable so that it has a mean of zero and a standard deviation of one. Formally, each observation is transformed by subtracting the sample mean and dividing by the sample standard deviation. In the R ecosystem, this logic is implemented in preprocessing tools such as `step_normalize()` from the **recipes** package. Standardization preserves the shape of the original distribution while putting variables on a comparable scale. It is particularly useful for models that are sensitive to the relative magnitude of predictors, such as linear models with regularization, support vector machines, and neural networks.\n\n**Normalization**, in a stricter sense, often refers to *min–max scaling*. This approach rescales variables to lie within a fixed interval, most commonly \\[0,1\\]. Each value is transformed based on the minimum and maximum observed in the training data. Min–max scaling is easy to interpret and is frequently used in algorithms where bounded inputs are desirable. However, it is also more sensitive to extreme values, since a single outlier can heavily influence the scaling range.\n\nA third commonly used approach is **robust scaling**, which relies on the median and the interquartile range (IQR) instead of the mean and standard deviation. By construction, this method is less affected by outliers and heavy-tailed distributions. Robust scaling is especially useful in real-world datasets where extreme values are not errors but genuine observations. At the same time, it is not a universal solution; in some data structures, robust measures may become unstable or uninformative.\n\nThe reason terminology becomes blurred in practice is simple: many practitioners use the word *normalization* as a generic label for “any kind of scaling.” As a result, two people may both say they normalized their data while having applied entirely different transformations. Throughout this article, we will avoid this ambiguity by explicitly stating which scaling method is used and why. This distinction is not pedantic—it is essential for understanding how scaling choices influence model behavior.\n\n## Why Is Normalization Necessary?\n\nThe necessity of normalization becomes clear once we recognize that many modeling techniques do not operate on raw variable values directly, but on **relationships derived from them**—such as distances, similarities, penalties, or variance directions. When predictors are measured on different scales, these derived quantities can be dominated by variables with larger numerical ranges, regardless of their substantive importance. In such cases, the model does not learn from the data structure itself, but from arbitrary measurement units.\n\nThis issue is most apparent in **distance-based methods** such as k-nearest neighbors (KNN) and K-means clustering. These algorithms rely explicitly on distance calculations, typically Euclidean distance. If one variable ranges between 0 and 1 while another ranges between 0 and 10,000, the latter will dominate the distance computation almost entirely. As a result, proximity is determined not by overall similarity but by the scale of a single variable. Normalization ensures that each predictor contributes to the distance metric in a balanced and interpretable way, allowing the algorithm to reflect genuine similarity rather than numerical magnitude.\n\nNormalization is equally critical in models that incorporate **regularization**, such as Ridge and Lasso regression. In these models, coefficients are penalized to control model complexity. However, the penalty term is directly tied to the scale of the predictors. If variables are not on comparable scales, the regularization mechanism will shrink coefficients unevenly, effectively penalizing some predictors more than others for reasons unrelated to their predictive relevance. Scaling aligns the predictors so that regularization operates as intended: as a constraint on model complexity rather than an artifact of measurement units.\n\nOther widely used techniques—including **support vector machines (SVMs)**, **neural networks**, and **principal component analysis (PCA)**—are also highly sensitive to scaling. In SVMs and neural networks, optimization procedures depend on gradients that are influenced by feature magnitudes, affecting both convergence speed and stability. In PCA, the directions of maximum variance are determined by the scale of the variables; without normalization, components may simply reflect variables with the largest variances rather than the most informative underlying structure. In all these cases, scaling is not an optional refinement but a prerequisite for meaningful model behavior.\n\nBy contrast, **tree-based models** such as decision trees, random forests, and gradient boosting machines are generally invariant to monotonic transformations of individual predictors. Since splits are based on ordering rather than distance or magnitude, scaling is often unnecessary for these methods. Nevertheless, this does not imply that normalization is universally irrelevant in tree-based pipelines. Hybrid workflows—where tree-based models are combined with distance-based components, rule-based similarity measures, or downstream models sensitive to scale—may still require careful consideration of scaling choices. The key point is not that normalization should always be applied, but that it should be applied **with respect to the assumptions of the modeling approach**.\n\nFrom a broader perspective, normalization plays a central role in modern predictive modeling workflows. As emphasized in the predictive modeling literature, preprocessing steps are not independent of the model; they are part of the modeling strategy itself. Scaling decisions shape how information is represented and, ultimately, how learning takes place. Understanding *why* normalization is necessary is therefore a prerequisite for deciding *when* and *how* it should be applied—a topic we address next.\n\n## Should Normalization Always Be Applied?\n\nA natural question at this point is whether normalization should be applied by default in every modeling task. The short answer is **no**. Normalization is not a universally beneficial preprocessing step; its usefulness depends on the assumptions and internal mechanics of the chosen model. Applying scaling blindly can be as problematic as ignoring it altogether. What is needed is a **decision framework** that links model characteristics to preprocessing choices.\n\nFor a large class of models, normalization is **strongly recommended**. This group includes distance-based methods such as k-nearest neighbors (KNN) and K-means clustering, as well as techniques like principal component analysis (PCA), support vector machines (SVMs), neural networks, and penalized regression models (Ridge, Lasso, Elastic Net). In all these cases, either distances, inner products, variance directions, or penalty terms play a central role. Without scaling, these mechanisms are dominated by variables with larger numerical ranges, leading to distorted learning behavior. For such models, normalization is not a refinement but a prerequisite for meaningful results.\n\nBy contrast, normalization is **generally unnecessary** for tree-based models such as decision trees, random forests, and gradient boosting machines (e.g., XGBoost, GBM). These models rely on recursive binary splits based on variable ordering rather than on distances or magnitudes. Since monotonic transformations do not affect the relative ordering of values, scaling typically has no impact on model performance. As a result, normalization is often omitted in purely tree-based pipelines without any loss of effectiveness.\n\nBetween these two extremes lies a set of models for which normalization is **context-dependent**. Ordinary linear regression, for example, does not require scaling for estimation itself, but normalization may still be useful for numerical stability, interpretability of coefficients, or comparability across predictors. Similarly, Naive Bayes models may or may not benefit from scaling depending on the assumed feature distributions and the types of variables involved. In these cases, the decision to normalize should be guided by the modeling objective rather than by a fixed rule.\n\nThe key takeaway is that normalization should be applied **with respect to the model’s assumptions**, not as a default preprocessing habit. To make this decision explicit, Table 1 summarizes common modeling approaches and whether normalization is typically required.\n\n### When Is Normalization Needed? A Model-Based Decision Table\n\n| Model / Method                | Is Normalization Recommended? | Rationale                                                                |\n|------------------|------------------|-----------------------------------|\n| KNN                           | Yes                           | Distance calculations are scale-sensitive                                |\n| K-means                       | Yes                           | Cluster assignment depends on distances                                  |\n| PCA                           | Yes                           | Variance directions dominated by scale                                   |\n| SVM                           | Yes                           | Optimization and margins depend on feature magnitude                     |\n| Neural Networks               | Yes                           | Gradient-based optimization is scale-sensitive                           |\n| Ridge / Lasso / Elastic Net   | Yes                           | Penalty terms depend on predictor scale                                  |\n| Linear Regression (OLS)       | Depends                       | Not required for estimation, but useful for stability and interpretation |\n| Naive Bayes                   | Depends                       | Depends on feature types and distributional assumptions                  |\n| Decision Trees                | No                            | Split rules depend on ordering, not scale                                |\n| Random Forest / GBM / XGBoost | No                            | Tree-based structure is scale-invariant                                  |\n\n## When Should Normalization Be Applied? Before or After the Train–Test Split?\n\nThis is the most critical question in the entire preprocessing workflow—and the point at which many otherwise sound analyses quietly go wrong. The issue is not *whether* normalization should be applied, but **when** it should be applied. At the center of this question lies a fundamental concept in predictive modeling: **data leakage**.\n\nData leakage occurs when information from outside the training set is used, directly or indirectly, during model training. In the context of normalization, leakage typically arises when scaling parameters—such as means and standard deviations (for standardization) or minimum and maximum values (for min–max scaling)—are estimated using the full dataset before splitting into training and test sets. Although this may appear harmless, it allows information from the test set to influence the preprocessing step, leading to overly optimistic performance estimates.\n\nThe correct principle is straightforward but non-negotiable:\\\n**scaling parameters must be learned exclusively from the training data**.\\\nOnce learned, the *same transformation*—with fixed parameters—must be applied to the test set and to any future, unseen data. This ensures that the test set truly represents new information and that model evaluation reflects genuine generalization rather than procedural artifacts.\n\nThis principle is central to modern modeling frameworks. In the **tidymodels/recipes** philosophy, preprocessing steps are *trained* on the training data and then *applied* consistently to all other datasets. Similarly, in the **caret** framework, preprocessing transformations are estimated from the training set and reused when predicting on new data. In both cases, preprocessing is treated as part of the model training process—not as an independent, preliminary operation.\n\nTo see why this distinction matters, consider the following conceptual comparison.\n\n### An Illustrative Example: Scaling Before vs. After the Split\n\nSuppose we have a dataset that we intend to split into training and test sets. We want to standardize a numeric predictor using z-score scaling.\n\n**Incorrect approach (scaling before the split):**\n\n1.  Compute the mean and standard deviation using the *entire dataset*.\n\n2.  Standardize all observations using these global parameters.\n\n3.  Split the scaled data into training and test sets.\n\n4.  Train and evaluate the model.\n\nAt first glance, this workflow seems efficient. However, the scaling parameters already incorporate information from the test set. The test data are no longer independent of the training process, even though they were not explicitly used to fit the model.\n\n**Correct approach (scaling after the split):**\n\n1.  Split the raw data into training and test sets.\n\n2.  Compute scaling parameters (mean, standard deviation, etc.) *using only the training set*.\n\n3.  Apply the learned transformation to the training set.\n\n4.  Apply the *same* transformation to the test set.\n\n5.  Train the model on the scaled training data and evaluate it on the scaled test data.\n\nIn practice, these two approaches can lead to noticeably different evaluation results. Models trained using the incorrect workflow often appear to perform better on the test set—not because they generalize better, but because the preprocessing step has already “seen” the test data. This difference is especially pronounced in smaller datasets, in datasets with strong distributional differences between training and test splits, or when extreme values are present.\n\nThe takeaway is unambiguous:\n\n> **Split the data first.\\\n> Fit preprocessing steps on the training data.\\\n> Apply the same transformations to the training and test sets.**\n\nAny deviation from this sequence undermines the validity of model evaluation, regardless of how sophisticated the modeling technique may be.\n\n## Common Normalization Methods and When to Use Them\n\nNormalization is not a single technique but a family of transformations, each designed to address a specific modeling concern. Choosing an appropriate method requires understanding **what problem the transformation is solving** and **which assumptions it implicitly makes**. In this section, we review the most commonly used scaling approaches, discuss their strengths and limitations, and clarify when each method is appropriate.\n\n### Z-score Standardization\n\nZ-score standardization rescales a variable so that it has a mean of zero and a standard deviation of one. Each observation $x_i$ is transformed as:\n\n$$\nz_i = \\frac{x_i - \\mu}{\\sigma},\n$$\n\nwhere $\\mu$ denotes the sample mean and $\\sigma$ the sample standard deviation, both estimated **from the training data only**.\n\n**Advantages.**\\\nZ-score standardization places variables on a comparable scale while preserving the shape of their original distributions. It is particularly suitable for models that rely on inner products, gradient-based optimization, or regularization (e.g., penalized linear models, SVMs, neural networks).\n\n**Limitations.**\\\nA widespread misconception is that standardization assumes normally distributed data. This is incorrect. Z-score scaling does **not** require normality; it only uses the first two moments of the distribution. However, it is sensitive to extreme values: large outliers can inflate $\\sigma$, thereby reducing the relative influence of most observations.\n\n**When to use.**\\\nA strong default choice when predictors differ substantially in scale and when outliers are either absent or have already been treated.\n\n------------------------------------------------------------------------\n\n### Min–Max (Range) Scaling\n\nMin–max scaling rescales variables to a fixed interval, most commonly $[0, 1]$. The transformation is:\n\n$$\nx_i^{*} = \\frac{x_i - \\min(x)}{\\max(x) - \\min(x)}.\n$$\n\n**Advantages.**\\\nIntuitive and ensures all transformed values lie within a predefined range. Often used when bounded inputs are desirable (e.g., some neural network settings).\n\n**Limitations.**\\\nHighly sensitive to extreme values: a single outlier can stretch the range and compress most observations. Also, when applied to test or future data, transformed values may fall outside $[0,1]$ if they exceed the training-set min/max. This is expected and must be handled in deployment.\n\n**When to use.**\\\nWhen input bounds are meaningful and the training data represent the likely range of future observations.\n\n------------------------------------------------------------------------\n\n### Robust Scaling (Median and IQR)\n\nRobust scaling replaces mean and standard deviation with the median and the interquartile range (IQR). The transformation is:\n\n$$\nx_i^{*} = \\frac{x_i - \\mathrm{median}(x)}{\\mathrm{IQR}(x)},\n$$\n\nwhere:\n\n$$\n\\mathrm{IQR}(x) = Q_{0.75} - Q_{0.25}.\n$$\n\n**Advantages.**\\\nLess affected by extreme values and heavy-tailed distributions; useful when outliers are meaningful rather than errors.\n\n**Limitations.**\\\nNot universally stable. In highly concentrated variables, $\\mathrm{IQR}(x)$ (or related robust measures such as MAD) may be zero or extremely small, making the transformation unstable or undefined. This must be checked explicitly.\n\n**When to use.**\\\nWhen outliers are present and structurally inherent, and you want scaling that is less sensitive to extremes.\n\n------------------------------------------------------------------------\n\n### Power Transformations Combined with Scaling (Box–Cox and Yeo–Johnson)\n\nPower transformations aim to stabilize variance and reduce skewness before scaling.\n\nThe **Box–Cox transformation** (for strictly positive data) is:\n\n$$\nx_i^{(\\lambda)} =\n\\begin{cases}\n\\frac{x_i^{\\lambda} - 1}{\\lambda}, & \\lambda \\neq 0, \\\\\\\\\n\\log(x_i), & \\lambda = 0.\n\\end{cases}\n$$\n\nThe **Yeo–Johnson transformation** (allows zero and negative values) is:\n\n$$\nx_i^{(\\lambda)} =\n\\begin{cases}\n\\frac{(x_i + 1)^{\\lambda} - 1}{\\lambda}, & x_i \\ge 0,\\ \\lambda \\neq 0, \\\\\\\\\n\\log(x_i + 1), & x_i \\ge 0,\\ \\lambda = 0, \\\\\\\\\n-\\frac{(-x_i + 1)^{2 - \\lambda} - 1}{2 - \\lambda}, & x_i < 0,\\ \\lambda \\neq 2, \\\\\\\\\n-\\log(-x_i + 1), & x_i < 0,\\ \\lambda = 2.\n\\end{cases}\n$$\n\n**Why combine with scaling?**\\\nPower transformations modify distributional shape but do not put variables on a common scale. After applying Box–Cox or Yeo–Johnson, variables are typically centered and scaled.\n\n**Order matters.**\\\nA practical default sequence is: **power transformation → centering → scaling**. Scaling before addressing skewness can weaken the effect of the transformation and complicate interpretation.\n\n**When to use.**\\\nWhen strong skewness or heteroscedasticity is present and when model assumptions or optimization benefit from more symmetric distributions.\n\n------------------------------------------------------------------------\n\n### Choosing a Method: No Single Best Answer\n\nThere is no universally optimal normalization method. Each approach reflects a trade-off between robustness, interpretability, and sensitivity to data characteristics. The appropriate choice depends on the model, the data structure, and the modeling objective.\n\n> The relevant question is not *\"Which normalization method is best?\"*\\\n> but *\"Which transformation aligns with my data and my model’s assumptions?\"*\n\n## Do Different Data Types Require Different Scaling Strategies?\n\nNormalization decisions should never be made independently of data types. Different variable types carry different semantic meanings, and applying the same scaling strategy indiscriminately can lead to misleading representations or unnecessary transformations. A principled preprocessing workflow therefore begins by distinguishing between variable types and understanding how each interacts with scaling.\n\n### Continuous Numeric Variables\n\nContinuous numeric variables are the primary candidates for normalization. When such variables are measured on different scales—such as income in thousands and proportions between 0 and 1—scaling is often essential for models that rely on distances, gradients, or regularization. Z-score standardization, min–max scaling, or robust scaling are all reasonable options, depending on the presence of outliers and the modeling objective.\n\nIn practice, most normalization methods are designed with continuous variables in mind, and applying them here rarely raises conceptual concerns. The main decision revolves around *which* scaling method is most appropriate, not *whether* scaling should be applied at all.\n\n------------------------------------------------------------------------\n\n### Count and Ordinal Numeric Variables\n\nSome numeric variables are technically continuous in storage but conceptually represent counts or ordered categories. Examples include the number of visits, rankings, Likert-scale responses, or discrete event counts. Treating such variables as purely continuous can be problematic, especially when their distributions are highly skewed or bounded at zero.\n\nIn these cases, applying a logarithmic or power transformation before scaling is often more appropriate than direct normalization. Power transformations can reduce skewness and stabilize variance, after which standardization or robust scaling may be applied. The key point is that **the meaning of the variable matters**: a difference of one unit in a count variable does not necessarily carry the same interpretation across its range.\n\n------------------------------------------------------------------------\n\n### Categorical Variables (Factors or Characters)\n\nCategorical variables should **never** be scaled directly. Their values represent qualitative categories rather than numerical magnitudes, and applying normalization to raw category codes is meaningless.\n\nWhen categorical variables are included in models that require numeric inputs, they must first be transformed using an encoding scheme such as one-hot (dummy) encoding. After encoding, the question of scaling arises again. In many cases, scaling encoded variables is unnecessary. However, in penalized regression models or distance-based methods, normalization of one-hot encoded variables may be beneficial to ensure that categorical and continuous predictors are treated on comparable scales.\n\nThe important distinction is that scaling applies **after encoding**, not before, and only when the model’s assumptions justify it.\n\n------------------------------------------------------------------------\n\n### Binary Variables (0/1 Indicators)\n\nBinary variables occupy a special position. Since they already lie on a fixed and interpretable scale, normalization is usually unnecessary and may even obscure interpretation. For many models, leaving binary indicators unchanged is the most transparent choice.\n\nThat said, binary variables often enter preprocessing pipelines automatically when a rule such as “scale all numeric predictors” is applied. In such cases, standardization will transform a 0/1 variable into values centered around zero with unit variance. While this does not usually harm model performance, it changes the interpretation of coefficients and can complicate downstream analysis.\n\nThis highlights an important practical lesson: automated preprocessing pipelines should be used with care. Even when a transformation is mathematically valid, it may not be conceptually desirable for all variable types.\n\n------------------------------------------------------------------------\n\n### Summary: Scaling Depends on Variable Meaning\n\nThe decision to normalize should always be guided by the *semantic role* of a variable, not merely by its storage type. Continuous measurements, counts, ordered responses, categorical indicators, and binary flags interact with scaling in fundamentally different ways. Effective preprocessing therefore requires more than applying a generic rule—it requires aligning transformations with the structure and meaning of the data.\n\n## Should All Variables Be Scaled?\n\nA common mistake in preprocessing workflows is to treat normalization as a blanket operation applied to every variable in the dataset. In reality, **not all variables should be scaled**, and doing so indiscriminately can reduce interpretability or even introduce unintended distortions. Scaling decisions must therefore be made at the variable level, guided by both statistical and semantic considerations.\n\n### The Target Variable (y)\n\nIn most predictive modeling tasks, the target variable should **not** be normalized. Scaling the response does not improve model estimation and often complicates interpretation, particularly in regression settings where coefficients and predictions are expected to be expressed in the original units.\n\nThere are, however, notable exceptions. In neural network regression or other optimization-heavy models, scaling the target variable can improve numerical stability and convergence behavior. In such cases, predictions must be transformed back to the original scale before evaluation and interpretation. Outside these specific contexts, leaving the target variable unchanged remains the standard and preferred practice.\n\n------------------------------------------------------------------------\n\n### Predictor Variables\n\nFor predictor variables, scaling should be applied selectively rather than universally.\n\n#### Numeric Predictors Only\n\nNormalization is meaningful only for numeric predictors. Applying scaling to non-numeric variables—either directly or implicitly through arbitrary numeric coding—has no conceptual justification. As discussed earlier, categorical variables must first be encoded, and even then, scaling is optional and model-dependent.\n\n#### Excluding Non-informative Numeric Variables\n\nNot all numeric variables carry meaningful quantitative information. Identifier variables such as IDs, account numbers, or arbitrary codes may be stored as numeric values but do not represent magnitudes or distances. Scaling such variables is meaningless and potentially harmful, as it introduces artificial structure where none exists. These variables should be excluded from the modeling process altogether, not merely from scaling.\n\n#### Handling Low-Variance Predictors\n\nVariables with extremely low or zero variance provide little to no information for modeling. Scaling such predictors does not solve the underlying problem; it merely rescales noise. In practice, low-variance and zero-variance predictors should be identified and removed **before** normalization.\n\nMany preprocessing frameworks formalize this step. For example, approaches based on the logic of zero-variance or near-zero-variance filtering (often referred to as `zv` or `nzv` steps) ensure that only informative predictors enter the scaling stage. This not only improves computational efficiency but also reduces the risk of numerical instability in downstream models.\n\n------------------------------------------------------------------------\n\n### A Practical Rule of Thumb\n\nA disciplined preprocessing workflow follows a clear sequence:\n\n1.  Identify and remove non-informative variables (IDs, constants, near-constants).\n2.  Select numeric predictors that represent meaningful quantities.\n3.  Apply appropriate scaling only to this subset.\n4.  Leave the target variable unscaled, unless there is a compelling model-specific reason to do otherwise.\n\nScaling is most effective when it is **deliberate and selective**, not automatic. Treating normalization as a universal operation may simplify code, but it rarely leads to better models.\n\n## Application Plan in R: Data and Modeling Scenario\n\nTo demonstrate the practical implications of normalization decisions, we use the **Ames Housing** dataset, a well-known benchmark dataset designed for predictive modeling. The dataset contains **2,930 observations** and a rich set of predictors describing residential properties in Ames, Iowa. These predictors span multiple data types, including continuous numeric variables, discrete counts, ordinal ratings, and categorical features. This diversity makes the dataset particularly suitable for illustrating how scaling interacts with different variable types.\n\nThe Ames Housing dataset is distributed within the **modeldata** package in the tidymodels ecosystem. It was explicitly curated for teaching and methodological demonstrations, ensuring a realistic but well-documented structure. The presence of variables measured on vastly different scales—such as living area, lot size, and quality scores—provides a natural setting for exploring the effects of normalization.\n\n### Modeling Objective\n\nThe primary goal of this application is **not** to optimize predictive performance, but to isolate and examine the impact of different normalization strategies. For this reason, the modeling task is intentionally kept simple. We focus on predicting the **sale price of a house** as a regression problem, using a fixed model specification across all experiments.\n\nThe model itself serves merely as a vehicle for comparison. By holding the model constant and varying only the preprocessing strategy, we can attribute differences in performance and behavior directly to scaling decisions rather than to model complexity or tuning choices.\n\n### Scope and Focus\n\nThroughout the application section, the emphasis remains firmly on preprocessing:\n\n-   the same training–test split is used across all scenarios,\n-   the same set of predictors is retained,\n-   the same model structure is applied.\n\nOnly the normalization strategy changes. This design allows us to answer a focused question:\n\n> *How much do scaling choices matter when everything else is kept equal?*\n\nBy structuring the analysis in this way, the results highlight normalization as an integral component of the modeling pipeline rather than a secondary technical detail.\n\n------------------------------------------------------------------------\n\n### Transition to Implementation\n\nIn the next section, we move from design to execution. We begin by defining a train–test split and establishing a baseline preprocessing workflow. From there, we introduce alternative normalization strategies and compare their effects using consistent evaluation criteria.\n\n### Data Access and Availability\n\nThe Ames Housing dataset used in this application is available through the **modeldata** package, which is part of the tidymodels ecosystem. No external download is required. Once the package is installed, the dataset can be accessed directly within R.\n\nThe dataset is provided for educational and methodological purposes and is accompanied by detailed documentation. For reference, the official description is available at:\n\n<https://modeldata.tidymodels.org/reference/ames.html>\n\nIn the next section, we load the dataset directly from the package and proceed with the train–test split and preprocessing workflow.\n\n## Implementation in R: Split, Baseline, and the Cost of Doing It Wrong\n\nIn this section, we operationalize the key principle introduced earlier:\n\n> **Split → fit preprocessing on train → apply to train/test**\n\nWe use the Ames Housing dataset from the `modeldata` package (no external download required) and compare three pipelines using the **same model**:\n\n1.  **Baseline (no scaling)**\n2.  **Incorrect scaling (data leakage)**: scaling parameters learned from the full dataset\n3.  **Correct scaling**: scaling parameters learned from the training set only\n\nThe goal is not to build the best possible model but to **isolate the effect of scaling decisions**.\n\n### Setup and Variable Selection\n\nBefore defining any model, we clarify what we are modeling and why these variables are used.\n\n**Modeling goal.**\\\nWe treat `Sale_Price` as the target variable and build a regression model that predicts house sale prices based on a small set of numeric predictors. The purpose is not to maximize predictive accuracy, but to create a controlled environment where the effect of scaling choices is easy to observe.\n\n**Why a small subset of predictors?**\\\nThe Ames dataset contains many variables, including categorical and ordinal predictors. For the normalization demonstrations, we intentionally select a compact set of **numeric** features with clearly different measurement scales. This makes the consequences of scaling (and data leakage) more visible and easier to interpret.\n\n**Selected variables (interpretation).**\n\n-   `Sale_Price`: sale price of the house (response variable).\n\n-   `Gr_Liv_Area`: above-ground living area (a size-related continuous measure).\n\n-   `Lot_Area`: lot size (typically much larger numeric range than living area).\n\n-   `Year_Built`: construction year (a temporal numeric variable).\n\n-   `Overall_Cond`: overall condition rating (an ordinal-like numeric score).\n\n-   `Latitude`, `Longitude`: geographic coordinates capturing location effects.\n\n------------------------------------------------------------------------\n\n### Load Data and Create a Working Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidymodels)\nlibrary(modeldata)\n\ndata(ames, package = \"modeldata\")\n\nset.seed(2026)\n\names_small <- ames %>%\n  dplyr::select(\n    Sale_Price,\n    Gr_Liv_Area,\n    Lot_Area,\n    Year_Built,\n    Overall_Cond,\n    Latitude,\n    Longitude\n  )\n\n# Missing-value check within the selected columns\names_small %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  tidyr::pivot_longer(everything(), names_to = \"variable\", values_to = \"n_missing\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  variable     n_missing\n  <chr>            <int>\n1 Sale_Price           0\n2 Gr_Liv_Area          0\n3 Lot_Area             0\n4 Year_Built           0\n5 Overall_Cond         0\n6 Latitude             0\n7 Longitude            0\n```\n\n\n:::\n:::\n\n\nThis step constructs a clean working dataset (`ames_small`) and confirms whether missing values exist in the selected columns. For the comparisons in the next sections, it is important that the pipelines differ only by preprocessing choices (e.g., scaling), not by inconsistent handling of missing data.\n\n### Train–Test Split and Evaluation Setup\n\nBefore discussing scaling, we must establish a clean evaluation setup. The key idea is simple:\n\n> **Split first. Then learn any preprocessing parameters from the training set only.**\n\nWithout a proper train–test split, we cannot meaningfully talk about generalization, and any comparison involving normalization risks becoming misleading.\n\n------------------------------------------------------------------------\n\n#### Create a Stratified Train–Test Split\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n\nsplit_obj <- initial_split(ames_small, prop = 0.80, strata = Sale_Price)\n\ntrain_data <- training(split_obj)\ntest_data  <- testing(split_obj)\n\nnrow(train_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2342\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(test_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 588\n```\n\n\n:::\n:::\n\n\n**What this does.**\n\n-   `prop = 0.80` assigns roughly 80% of the data to training and 20% to testing.\n\n-   `strata = Sale_Price` performs a *stratified* split based on the target variable.\\\n    This reduces the risk that the test set ends up with an atypical concentration of very low or very high prices—something that can easily happen with skewed targets like house prices.\n\n**How to interpret the output.**\n\n-   If the full dataset contains 2,930 observations, you should see approximately:\n\n```         \n-    training: 2,342 rows\n\n-    test: 588 rows\n```\n\nThis corresponds closely to the intended 80/20 split and indicates that no unintended row loss occurred during preprocessing.\n\n#### Sanity Check: Is the Target Distribution Similar Across Splits?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  train_data %>% mutate(split = \"train\"),\n  test_data  %>% mutate(split = \"test\")\n) %>%\n  ggplot(aes(x = Sale_Price, fill = split)) +\n  geom_histogram(bins = 40, alpha = 0.7, color = \"white\") +\n  facet_wrap(~ split, scales = \"free_y\") +\n  scale_fill_manual(\n    values = c(train = \"#1f77b4\", test = \"#ff7f0e\")\n  ) +\n  labs(\n    title = \"Sale_Price distribution after train–test split\",\n    x = \"Sale_Price\",\n    y = \"Count\",\n    fill = \"Data split\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n**What to look for.**\n\n-   Both distributions should be right-skewed with a similar central mass.\n\n-   There should be no strong imbalance where most expensive (or cheapest) homes appear in only one split.\n\nIn the plot, the overall shapes are highly similar and the mid-range is well represented in both sets, indicating that stratification preserved the structure of the target variable across splits.\n\n#### Optional Check: Quick Summary Statistics\n\nThis is a compact numerical confirmation of what the plot shows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_summary <- train_data %>%\nsummarise(\nsplit = \"train\",\nn = n(),\nmean = mean(Sale_Price),\nmedian = median(Sale_Price),\nsd = sd(Sale_Price),\nmin = min(Sale_Price),\nmax = max(Sale_Price)\n)\n\ntest_summary <- test_data %>%\nsummarise(\nsplit = \"test\",\nn = n(),\nmean = mean(Sale_Price),\nmedian = median(Sale_Price),\nsd = sd(Sale_Price),\nmin = min(Sale_Price),\nmax = max(Sale_Price)\n)\n\nbind_rows(train_summary, test_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  split     n    mean median     sd   min    max\n  <chr> <int>   <dbl>  <dbl>  <dbl> <int>  <int>\n1 train  2342 180447. 160000 79157. 12789 755000\n2 test    588 182185. 160500 82784. 35311 625000\n```\n\n\n:::\n:::\n\n\n**How to interpret this.**\n\n-   Small differences between train and test are expected.\n\n-   Large gaps—especially in the median—may indicate an unbalanced split.\n\nYour summaries show nearly identical means and medians (train: 180,447 / 160,000; test: 182,185 / 160,500) and similar standard deviations, supporting the conclusion that the split is well balanced. Differences in the maximum values are expected due to rare high-priced homes and do not indicate a problematic split.\n\nThe train–test split is well balanced and suitable for downstream modeling. The test set can be treated as a genuine proxy for unseen data, allowing us to evaluate normalization strategies without confounding effects from an unbalanced split.\n\n### Model Specification: A Scale-Sensitive Baseline\n\nBefore comparing different normalization strategies, we must fix the modeling component of the pipeline. This ensures that any performance differences observed later can be attributed to preprocessing choices rather than to changes in the model itself.\n\n**Why KNN Regression?**\n\nWe deliberately choose **k-nearest neighbors (KNN) regression** for this demonstration. The reason is methodological, not practical.\n\nKNN is a **distance-based algorithm**: predictions are determined by the distances between observations in the feature space. As a result, KNN is highly sensitive to the scale of the predictors. Variables with larger numeric ranges can dominate distance calculations, even if they are not substantively more important.\n\nThis property makes KNN an ideal diagnostic tool for studying the effects of scaling.\n\n------------------------------------------------------------------------\n\n#### Model Specification\n\nWe define a single KNN model that will be used in all subsequent scenarios.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_spec <- nearest_neighbor(\n  neighbors = 15,\n  weight_func = \"rectangular\"\n) %>%\n  set_engine(\"kknn\") %>%\n  set_mode(\"regression\")\n```\n:::\n\n\n**Commentary.**\n\n-   The number of neighbors is fixed at 15 to reduce variance while maintaining locality.\n\n-   No hyperparameter tuning is performed, as optimization is not the goal here.\n\n-   This model specification will remain unchanged across all preprocessing pipelines.\n\n### Scenario A — Baseline: No Scaling\n\nWe begin with a baseline workflow in which **no scaling is applied**. This provides a reference point against which all normalized pipelines will be compared.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec_none <- recipe(Sale_Price ~ ., data = train_data)\n\nwf_none <- workflow() %>%\nadd_recipe(rec_none) %>%\nadd_model(knn_spec)\n\nfit_none <- fit(wf_none, data = train_data)\n```\n:::\n\n\n::: callout-note\n> **Note on model engines.**\\\n> In the tidymodels ecosystem, model specifications are defined independently of the underlying computational engines. Although we specify the KNN model via `nearest_neighbor()`, the actual implementation is provided by the `kknn` package.\n>\n> If the package is not installed, fitting the model will fail. To proceed, install and load the required engine:\n>\n> ``` r\n> install.packages(\"kknn\")\n> library(kknn)\n> ```\n>\n> This separation between model specification and engine implementation is intentional and allows tidymodels to remain modular and extensible.\n:::\n\n#### **Evaluate on the Test Set**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_none <- predict(fit_none, test_data) %>%\nbind_cols(test_data %>% dplyr::select(Sale_Price))\n\nmetrics_none <- yardstick::metrics(\npred_none,\ntruth = Sale_Price,\nestimate = .pred\n)\n\nmetrics_none\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard   35643.   \n2 rsq     standard       0.816\n3 mae     standard   23726.   \n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\nThese values are not “good” or “bad” in isolation; what matters is that they provide a **stable reference**. At this stage, the model operates on raw predictor scales. For a distance-based method like KNN, this implies:\n\n-   Predictors with larger numeric ranges (e.g., `Lot_Area`) can disproportionately influence distance calculations.\n\n-   Smaller-range variables (e.g., ordinal-like `Overall_Cond`) may contribute less than intended.\n\n-   The model’s behavior is therefore partially shaped by measurement units, not only by predictive structure.\n\nThis is exactly why KNN is a useful diagnostic tool in a normalization-focused article: if scaling matters, we should see clear changes relative to this baseline once we introduce normalization.\n\nNext, we introduce scaling—but **incorrectly** on purpose. We will apply normalization *before* the train–test split (i.e., using information from the full dataset). This creates **data leakage** and can lead to deceptively improved test performance.\n\nAfter that, we will implement the correct workflow (fit scaling parameters on the training set only) and compare all scenarios side by side.\n\n### Scenario B — Incorrect Normalization (Data Leakage)\n\nIn this scenario, we intentionally apply normalization **the wrong way**: we learn scaling parameters from the full dataset (including what will become the test set). This contaminates the evaluation because preprocessing has already “seen” information from the test distribution.\n\nThe goal is not to recommend this approach, but to demonstrate how easily leakage can happen—and how it can artificially improve test metrics.\n\n#### Leakage Pipeline: Normalize Using Full Data\n\nThe `step_normalize()` operation applies only to numeric predictors. In our dataset, `Overall_Cond` is stored as a factor (ordinal-like category), so it must not be normalized directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec_leak <- recipe(Sale_Price ~ ., data = ames_small) %>%\n  step_normalize(all_numeric_predictors())\n\n# WRONG on purpose: prepping on full data (leakage), but now type-safe\nprep_leak <- prep(rec_leak, training = ames_small)\n\ntrain_leak <- bake(prep_leak, new_data = train_data)\ntest_leak  <- bake(prep_leak, new_data = test_data)\n\nwf_leak <- workflow() %>%\n  add_model(knn_spec) %>%\n  add_formula(Sale_Price ~ .)\n\nfit_leak <- fit(wf_leak, data = train_leak)\n\npred_leak <- predict(fit_leak, test_leak) %>%\n  bind_cols(test_leak %>% dplyr::select(Sale_Price))\n\nmetrics_leak <- yardstick::metrics(pred_leak, truth = Sale_Price, estimate = .pred)\nmetrics_leak\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard   37036.   \n2 rsq     standard       0.801\n3 mae     standard   24411.   \n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\nThe performance obtained under this scenario reflects the consequences of **incorrect normalization with data leakage**.\n\nCompared to the baseline (no scaling), all three metrics deteriorate. This indicates that learning normalization parameters from the full dataset does **not** automatically lead to better predictive performance. In this case, the leakage-induced transformation appears to distort the distance structure in a way that is unfavorable for KNN.\n\nThis result is particularly instructive because it challenges a common misconception:\\\n**data leakage does not necessarily inflate performance metrics**. Its effect depends on the interaction between the preprocessing step, the data distribution, and the model. What leakage *does* guarantee, however, is that the evaluation is no longer valid.\n\nEven if the metrics had improved under this scenario, they could not be trusted as estimates of out-of-sample performance. The test data would no longer represent genuinely unseen observations, since information from their distribution had already been incorporated during preprocessing.\n\nAt this point, two important conclusions can be drawn:\n\n1.  Scaling decisions materially affect model behavior, especially for distance-based methods.\n\n2.  The timing of scaling—*when* parameters are learned—is as critical as *whether* scaling is applied at all.\n\nIn the next scenario, we apply normalization correctly by estimating scaling parameters using the training data only and then applying them unchanged to the test set. This will provide the only defensible estimate of generalization performance among the normalization strategies considered.\n\n### Scenario C — Correct Normalization (Train-Only Scaling)\n\nIn this final preprocessing scenario, normalization parameters are learned **exclusively from the training data** and then applied consistently to both the training and test sets.\n\nThis workflow adheres to the core principle of leakage-free modeling.\n\n#### Correct Pipeline: Normalize Using Training Data Only\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec_ok <- recipe(Sale_Price ~ ., data = train_data) %>%\n  step_normalize(all_numeric_predictors())\n\nwf_ok <- workflow() %>%\n  add_recipe(rec_ok) %>%\n  add_model(knn_spec)\n\nfit_ok <- fit(wf_ok, data = train_data)\n\npred_ok <- predict(fit_ok, test_data) %>%\n  bind_cols(test_data %>% dplyr::select(Sale_Price))\n\nmetrics_ok <- yardstick::metrics(pred_ok, truth = Sale_Price, estimate = .pred)\n\nmetrics_ok\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard   35643.   \n2 rsq     standard       0.816\n3 mae     standard   23726.   \n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\nThis scenario represents the **correct normalization workflow**, where scaling parameters are learned exclusively from the training data and then applied unchanged to the test set. The results are **identical to the no-scaling baseline**. This finding is highly informative.\n\nFirst, it confirms that normalization itself does not automatically improve model performance. When applied correctly, scaling does not inject additional information into the modeling process; it merely changes the representation of the data. If the underlying distance structure relevant for prediction is already dominated by certain predictors, scaling may have little to no effect on performance.\n\nSecond, the contrast with the leakage scenario is crucial. In Scenario B, incorrect normalization degraded performance, while in this scenario, correct normalization restores the metrics to their baseline levels. This symmetry reinforces the core message of this article:\\\n**the validity of preprocessing matters more than the apparent gains it may produce.**\n\nThird, these results highlight an often-overlooked point: the impact of scaling is model- and data-dependent. For this particular subset of predictors and this KNN configuration, normalization neither helps nor harms when applied correctly. In other settings—different feature sets, different distance metrics, or different models—the effect could be substantial.\n\nThe key takeaway is therefore not that scaling is unnecessary, but that it must be:\n\napplied deliberately,\n\nrestricted to appropriate variables,\n\nand learned at the correct stage of the modeling workflow.\n\nWith all three scenarios evaluated, we can now compare them side by side and distill the practical lessons they offer.\n\n### Results Comparison\n\nWith all three scenarios evaluated, we now compare them side by side. Since the model and data split were held constant, any differences observed here are entirely attributable to preprocessing choices.\n\n#### Performance Summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults_tbl <- dplyr::bind_rows(\n  metrics_none %>% mutate(scenario = \"A — No Scaling\"),\n  metrics_leak %>% mutate(scenario = \"B — Incorrect Scaling (Leakage)\"),\n  metrics_ok   %>% mutate(scenario = \"C — Correct Scaling (Train-Only)\")\n) %>%\n  dplyr::select(scenario, .metric, .estimate) %>%\n  tidyr::pivot_wider(\n    names_from = .metric,\n    values_from = .estimate\n  )\n\nresults_tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  scenario                           rmse   rsq    mae\n  <chr>                             <dbl> <dbl>  <dbl>\n1 A — No Scaling                   35643. 0.816 23726.\n2 B — Incorrect Scaling (Leakage)  37036. 0.801 24411.\n3 C — Correct Scaling (Train-Only) 35643. 0.816 23726.\n```\n\n\n:::\n:::\n\n\nThis table summarizes test-set performance across all scenarios.\n\n-   **Scenario A (No Scaling)** serves as the baseline.\n\n-   **Scenario B (Incorrect Scaling with Leakage)** shows degraded performance.\n\n-   **Scenario C (Correct Scaling)** reproduces the baseline results exactly.\n\n#### Visual Comparison (RMSE)\n\nTo make the differences easier to interpret, we visualize RMSE across scenarios.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults_tbl %>%\nggplot(aes(x = scenario, y = rmse, fill = scenario)) +\ngeom_col(alpha = 0.8) +\nscale_fill_manual(\nvalues = c(\n\"A — No Scaling\" = \"#1f77b4\",\n\"B — Incorrect Scaling (Leakage)\" = \"#d62728\",\n\"C — Correct Scaling (Train-Only)\" = \"#2ca02c\"\n)\n) +\nlabs(\ntitle = \"RMSE comparison across preprocessing scenarios\",\nx = \"Preprocessing scenario\",\ny = \"RMSE\"\n) +\ntheme_minimal() +\ntheme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n#### Interpretation\n\nSeveral important conclusions emerge from this comparison.\n\nFirst, **normalization does not inherently improve performance**. When applied correctly (Scenario C), scaling neither improves nor degrades performance relative to the no-scaling baseline. This confirms that normalization is a representational transformation, not a source of predictive signal.\n\nSecond, **incorrect normalization can be harmful**. Scenario B demonstrates that learning scaling parameters from the full dataset can distort the feature space in ways that negatively affect model behavior. Even more importantly, this scenario yields an invalid evaluation, regardless of whether the metrics appear better or worse.\n\nThird, these results reinforce a central theme of this article:\\\n**the correctness of the preprocessing workflow matters more than the choice of preprocessing method itself**.\n\nIn practice, this means that:\n\n-   scaling should be applied only when it aligns with the model’s assumptions,\n\n-   preprocessing parameters must be learned exclusively from training data,\n\n-   and any apparent performance gains should be scrutinized for potential leakage.\n\n### Practical Takeaways from the Application\n\nFrom this controlled experiment, we can distill three practical lessons:\n\n1.  **Do not expect normalization to be a silver bullet.** Its impact depends on the model, the data, and the feature set.\n\n2.  **Never compromise the train–test boundary.** Leakage can invalidate results even when performance does not improve.\n\n3.  **Treat preprocessing as part of the model.** Decisions about scaling are modeling decisions, not technical afterthoughts.\n\nThese lessons generalize beyond KNN and apply to any workflow involving scale-sensitive models and data transformations.\n\n## Discussion and Conclusion\n\nNormalization is often introduced as a routine preprocessing step, applied almost reflexively before modeling. This article has argued—and demonstrated—that such a view is incomplete. Normalization is not a purely technical adjustment; it is a **modeling decision** whose consequences depend on the interaction between data, model assumptions, and evaluation design.\n\nFrom a theoretical perspective, scaling matters because many learning algorithms are sensitive to the relative magnitudes of predictors. Distance-based methods, regularized models, kernel methods, and optimization-driven algorithms implicitly encode assumptions about scale. Ignoring these assumptions can distort model behavior, while respecting them can improve stability and interpretability. At the same time, scaling does not create new information. It reshapes how existing information is represented.\n\nThe empirical application using the Ames Housing dataset reinforced these points. By holding the model and data split constant and varying only the preprocessing strategy, we isolated the effect of normalization decisions. Three key findings emerged.\n\nFirst, **normalization does not guarantee performance improvements**. In the correct workflow, scaling reproduced the baseline results exactly. This confirms that normalization should not be expected to “fix” a model by itself. Its role is conditional and context-dependent.\n\nSecond, **incorrect normalization compromises validity**. Learning scaling parameters from the full dataset—thereby introducing data leakage—altered model behavior and degraded performance in this example. More importantly, even if the metrics had improved, the evaluation would have been invalid. Leakage undermines the fundamental purpose of a test set: to approximate unseen data.\n\nThird, **the timing of preprocessing is as important as the method chosen**. The difference between valid and invalid evaluation hinged not on whether scaling was applied, but on *when* its parameters were learned. This distinction is often overlooked in practice, yet it is central to trustworthy modeling.\n\nTaken together, these results support a broader principle: preprocessing steps should be treated as integral components of the modeling pipeline, not as detached technical preliminaries. Decisions about normalization should be guided by model assumptions, data characteristics, and evaluation design—not by habit or generic checklists.\n\nIn practical terms, this leads to a simple but robust rule:\n\n> **Split the data first. Learn preprocessing parameters from the training set only. Apply the same transformations to all future data.**\n\nNormalization, when used deliberately and correctly, is a powerful tool. When applied mechanically or at the wrong stage, it can mislead. Understanding this distinction is essential for building models that are not only accurate, but also scientifically defensible.\n\n------------------------------------------------------------------------\n\n## References\n\n-   Hastie, T., Tibshirani, R., & Friedman, J. (2009).\\\n    *The Elements of Statistical Learning: Data Mining, Inference, and Prediction*. Springer.\n\n-   Kuhn, M., & Johnson, K. (2013).\\\n    *Applied Predictive Modeling*. Springer.\n\n-   Kuhn, M., & Wickham, H. (2023).\\\n    *Tidymodels: A Collection of Packages for Modeling and Machine Learning Using Tidyverse Principles*.\\\n    <https://www.tidymodels.org/>\n\n-   Tidymodels Recipes Documentation.\\\n    <https://recipes.tidymodels.org/>\n\n-   Kuhn, M. (Caret package documentation).\\\n    <https://topepo.github.io/caret/>\n\n-   Modeldata package documentation (Ames Housing dataset).\\\n    <https://modeldata.tidymodels.org/reference/ames.html>\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}