<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="M. Fatih Tüzen">
<meta name="dcterms.date" content="2025-07-11">

<title>Standard Deviation vs.&nbsp;Standard Error: Meaning, Misuse, and the Math Behind the Confusion – A Statistician's R Notebook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d166b450ba5a8e9f7a0ab969bf6592c1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f3c2ea88cadbcfb37ba28ffa2c97cfc1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ae2d0dcda2edce4ab590422bb373b64f.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">A Statistician’s R Notebook</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/MFatihTuzen"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/dr-m-fatih-t-2b2a4328/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-blogroll" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">BlogRoll</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-blogroll">    
        <li>
    <a class="dropdown-item" href="https://www.r-bloggers.com/">
 <span class="dropdown-text">R-bloggers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://community.rstudio.com/">
 <span class="dropdown-text">R-Studio Community</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://rweekly.org/">
 <span class="dropdown-text">R weekly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://allisonhorst.com/allison-horst">
 <span class="dropdown-text">Allison Horst</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/topics/r">
 <span class="dropdown-text">Github R Topics</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Standard Deviation vs.&nbsp;Standard Error: Meaning, Misuse, and the Math Behind the Confusion</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                                <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Data Analysis</div>
                <div class="quarto-category">Standard Deviation</div>
                <div class="quarto-category">Standard Error</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>M. Fatih Tüzen </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 11, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#introduction-why-this-confusion-still-matters" id="toc-introduction-why-this-confusion-still-matters" class="nav-link active" data-scroll-target="#introduction-why-this-confusion-still-matters"><span class="header-section-number">1</span> Introduction: Why This Confusion Still Matters</a></li>
  <li><a href="#definitions-and-mathematical-foundation" id="toc-definitions-and-mathematical-foundation" class="nav-link" data-scroll-target="#definitions-and-mathematical-foundation"><span class="header-section-number">2</span> Definitions and Mathematical Foundation</a></li>
  <li><a href="#visualizing-the-difference-with-r-simulation-and-interpretation" id="toc-visualizing-the-difference-with-r-simulation-and-interpretation" class="nav-link" data-scroll-target="#visualizing-the-difference-with-r-simulation-and-interpretation"><span class="header-section-number">3</span> Visualizing the Difference with R: Simulation and Interpretation</a></li>
  <li><a href="#common-mistakes-and-misinterpretations" id="toc-common-mistakes-and-misinterpretations" class="nav-link" data-scroll-target="#common-mistakes-and-misinterpretations"><span class="header-section-number">4</span> Common Mistakes and Misinterpretations</a></li>
  <li><a href="#a-real-world-example-monthly-spending-survey-in-usd" id="toc-a-real-world-example-monthly-spending-survey-in-usd" class="nav-link" data-scroll-target="#a-real-world-example-monthly-spending-survey-in-usd"><span class="header-section-number">5</span> A Real-World Example: Monthly Spending Survey in USD</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sd_vs_se.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>The left side illustrates standard deviation as the spread of individual data values around the population mean (μ). The right side shows standard error as the variability in sample means (x̄) obtained from repeated sampling. Notice how the SE distribution is narrower—it represents uncertainty in the estimate, not variability in the raw data.</figcaption>
</figure>
</div>
<section id="introduction-why-this-confusion-still-matters" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction-why-this-confusion-still-matters"><span class="header-section-number">1</span> Introduction: Why This Confusion Still Matters</h2>
<p>In the world of data analysis and statistics, <strong>standard deviation (SD)</strong> and <strong>standard error (SE)</strong> are two concepts that are often misunderstood or—worse—used interchangeably. This confusion isn’t just academic: misinterpreting these two measures can lead to poor conclusions, misleading visualizations, and incorrect inferences, especially in reports intended for non-technical audiences.</p>
<p>Think about this: you read a news article stating that <em>“the average income of a sample group is $3,000 with a standard error of $500.”</em> But then another article says <em>“the same average income with a standard deviation of $500.”</em> Should your level of confidence change? Absolutely—because they tell two fundamentally different stories.</p>
<p>This article aims to:</p>
<ul>
<li>Define and differentiate standard deviation and standard error,</li>
<li>Explore their mathematical foundations,</li>
<li>Demonstrate their practical implications with real R code and visuals,</li>
<li>Warn about common pitfalls and interpretation mistakes.</li>
</ul>
<p>By the end of this post, you’ll not only <strong>understand the difference</strong> but also <strong>know exactly when and why each metric matters</strong>.</p>
</section>
<section id="definitions-and-mathematical-foundation" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="definitions-and-mathematical-foundation"><span class="header-section-number">2</span> Definitions and Mathematical Foundation</h2>
<p>Understanding the difference between <strong>standard deviation</strong> and <strong>standard error</strong> requires going beyond surface-level definitions. While they are mathematically related, they answer fundamentally different questions.</p>
<section id="standard-deviation-sd" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="standard-deviation-sd"><span class="header-section-number">2.1</span> Standard Deviation (SD)</h3>
<p>Standard deviation is a measure of <strong>variability</strong> or <strong>dispersion</strong> within a single dataset. It tells us how far individual observations tend to deviate from the sample (or population) mean.</p>
<p>Mathematically, for a sample of size <span class="math inline">\(n\)</span>, the sample standard deviation is given by:</p>
<p><span class="math display">\[
s = \sqrt{ \frac{1}{n - 1} \sum_{i=1}^{n} (x_i - \bar{x})^2 }
\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(x_i\)</span>: Each data point</li>
<li><span class="math inline">\(\bar{x}\)</span>: Sample mean</li>
<li><span class="math inline">\(n\)</span>: Number of observations</li>
</ul>
<p>Standard deviation is widely used in descriptive statistics to understand how <strong>spread out</strong> the values in a dataset are. A large SD implies high variability, while a small SD suggests the values are clustered closely around the mean.</p>
<blockquote class="blockquote">
<p>📌 <strong>Use case</strong>: “How much do individual students’ test scores vary from the class average?”</p>
</blockquote>
</section>
<section id="standard-error-se" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="standard-error-se"><span class="header-section-number">2.2</span> Standard Error (SE)</h3>
<p>Standard error, in contrast, is a measure of <strong>precision</strong>—specifically, the precision of an estimate like the sample mean. It tells us how much the <strong>sample mean</strong> would vary if we repeatedly drew samples from the population.</p>
<p>It is defined as:</p>
<p><span class="math display">\[
\text{SE} = \frac{s}{\sqrt{n}}
\]</span></p>
<p>As you can see, SE is directly related to the standard deviation but scaled down by the square root of the sample size. This reflects the idea that <strong>more data gives more precise estimates</strong>.</p>
<blockquote class="blockquote">
<p>📌 <strong>Use case</strong>: “How much uncertainty is there in the sample mean as an estimate of the population mean?”</p>
</blockquote>
<hr>
<p>In short:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>Measures</th>
<th>Based on</th>
<th>Affected by Sample Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Standard Deviation</td>
<td>Spread of individual data points</td>
<td>Individual observations</td>
<td>❌ No</td>
</tr>
<tr class="even">
<td>Standard Error</td>
<td>Uncertainty in the sample mean</td>
<td>Sampling distribution</td>
<td>✅ Yes</td>
</tr>
</tbody>
</table>
<p>Understanding this distinction is critical for drawing correct conclusions—especially in inferential statistics, confidence intervals, and hypothesis testing.</p>
</section>
</section>
<section id="visualizing-the-difference-with-r-simulation-and-interpretation" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="visualizing-the-difference-with-r-simulation-and-interpretation"><span class="header-section-number">3</span> Visualizing the Difference with R: Simulation and Interpretation</h2>
<p>Let’s use R to <strong>visualize</strong> and <strong>truly understand</strong> the difference between standard deviation and standard error.</p>
<p>We’ll start by generating a single random sample from a known population and examining the spread of individual values. Then, we’ll simulate multiple samples to show how the sample means vary—and how that variation reflects the standard error.</p>
<section id="standard-deviation-spread-of-values-within-a-sample" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="standard-deviation-spread-of-values-within-a-sample"><span class="header-section-number">3.1</span> Standard Deviation: Spread of Values Within a Sample</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sample_data <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We generate 50 values from a normal distribution with a mean of 100 and a standard deviation of 15. This mimics a situation like measuring the heights, weights, or incomes of 50 individuals.</p>
<p>Let’s visualize how these values are distributed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> sample_data), <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..), <span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(x)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Standard Deviation: Spread of Individual Values"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What This Graph Shows</strong></p>
<ul>
<li><p>The histogram shows the <strong>distribution of raw data</strong> from our single sample.</p></li>
<li><p>The black curve is a <strong>kernel density estimate</strong>, giving us a smooth representation of the distribution.</p></li>
<li><p>The red dashed line marks the <strong>sample mean</strong>.</p></li>
<li><p>The <strong>spread around this mean</strong>—the “thickness” of the histogram—is what the <strong>standard deviation</strong> quantifies.</p></li>
</ul>
<p>So, in simple terms: <strong>standard deviation tells us how much individual values differ from their mean in one sample</strong>. It answers the question:</p>
<blockquote class="blockquote">
<p>“Are most values close to the average, or are they all over the place?”</p>
</blockquote>
</section>
<section id="standard-error-spread-of-sample-means-across-repeated-samples" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="standard-error-spread-of-sample-means-across-repeated-samples"><span class="header-section-number">3.2</span> Standard Error: Spread of Sample Means Across Repeated Samples</h3>
<p>Now let’s go one level deeper. Instead of looking at one sample, let’s imagine we repeatedly draw many samples from the same population, each of size 50, and record their means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sample_means <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">mean</span>(<span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s see how those means are distributed:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">mean =</span> sample_means), <span class="fu">aes</span>(<span class="at">x =</span> mean)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..), <span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"darkorange"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(mean)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Standard Error: Variability of Sample Means"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Sample Mean"</span>, <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What This Graph Shows</strong></p>
<ul>
<li><p>Each bar in the histogram represents the <strong>frequency of sample means</strong> in a small range.</p></li>
<li><p>The curve again shows the <strong>estimated density</strong> of the sample means.</p></li>
<li><p>The red dashed line is the <strong>grand mean</strong> of all 1,000 sample means—it should be close to 100.</p></li>
<li><p>Unlike the previous graph, here we don’t see individual values but <strong>mean values from many samples</strong>.</p></li>
</ul>
<p>This distribution is known as the <strong>sampling distribution of the sample mean</strong>.</p>
<p>And the <strong>standard deviation of this distribution is the standard error</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>se_estimate <span class="ot">&lt;-</span> <span class="fu">sd</span>(sample_means)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>se_estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.113943</code></pre>
</div>
</div>
</section>
<section id="interpretation-two-types-of-spread-two-different-questions" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="interpretation-two-types-of-spread-two-different-questions"><span class="header-section-number">3.3</span> Interpretation: Two Types of Spread, Two Different Questions</h3>
<p>Let’s pause and reflect on what we’ve seen so far.</p>
<p>Although <strong>standard deviation</strong> and <strong>standard error</strong> are both measures of “spread,” they describe very different things, answer different questions, and are used in different contexts.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 34%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>What it Measures</th>
<th>Based on…</th>
<th>Changes with Sample Size (<span class="math inline">\(n\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Standard Deviation</td>
<td>Spread of individual data values</td>
<td>Single sample</td>
<td>❌ No</td>
</tr>
<tr class="even">
<td>Standard Error</td>
<td>Spread of sample means across repeated samples</td>
<td>Sampling distribution</td>
<td>✅ Yes</td>
</tr>
</tbody>
</table>
<hr>
<section id="summary-of-interpretation" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="summary-of-interpretation"><span class="header-section-number">3.3.1</span> Summary of Interpretation</h4>
<ul>
<li><p><strong>Standard deviation (SD)</strong> tells us:<br>
&gt; <em>“How much do individual values differ from the average within a sample?”</em></p></li>
<li><p><strong>Standard error (SE)</strong> tells us:<br>
&gt; <em>“How much would the sample average vary if we repeated the sampling?”</em></p></li>
</ul>
<p>In other words:</p>
<ul>
<li><strong>SD measures natural variability</strong> among individuals (or observations).</li>
<li><strong>SE measures the statistical uncertainty</strong> of an estimate, usually the sample mean.</li>
</ul>
<p>This difference is not just semantic—it has <strong>critical consequences</strong> for data interpretation:</p>
<ul>
<li>You use <strong>SD</strong> when describing the spread of your sample or population.</li>
<li>You use <strong>SE</strong> when making inferences, estimating confidence intervals, or assessing how trustworthy your sample statistic is.</li>
</ul>
</section>
<section id="the-mathematical-connection" class="level4" data-number="3.3.2">
<h4 data-number="3.3.2" class="anchored" data-anchor-id="the-mathematical-connection"><span class="header-section-number">3.3.2</span> The Mathematical Connection</h4>
<p>As we saw earlier, the standard error is mathematically derived from the standard deviation:</p>
<p><span class="math display">\[
\text{SE} = \frac{s}{\sqrt{n}}
\]</span></p>
<p>This formula reveals a fundamental principle in statistics:</p>
<ul>
<li>The more data you collect (larger <span class="math inline">\(n\)</span>), the <strong>more stable</strong> your sample mean becomes.</li>
<li>However, the <strong>variability within the sample</strong> (standard deviation <span class="math inline">\(s\)</span>) may remain roughly the same—because it depends on the population, not on how many observations you took.</li>
</ul>
<blockquote class="blockquote">
<p>🧠 <strong>Key insight</strong>:<br>
<strong>Standard deviation reflects the reality of your data.</strong><br>
<strong>Standard error reflects your uncertainty about the mean.</strong></p>
</blockquote>
</section>
</section>
</section>
<section id="common-mistakes-and-misinterpretations" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="common-mistakes-and-misinterpretations"><span class="header-section-number">4</span> Common Mistakes and Misinterpretations</h2>
<p>Despite their differences, standard deviation and standard error are frequently confused—even in academic papers, business reports, and media articles. Below are some of the most common mistakes and why they matter.</p>
<section id="mistake-1-using-standard-error-instead-of-standard-deviation-in-descriptive-summaries" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="mistake-1-using-standard-error-instead-of-standard-deviation-in-descriptive-summaries"><span class="header-section-number">4.1</span> Mistake 1: Using Standard Error Instead of Standard Deviation in Descriptive Summaries</h3>
<p>A classic mistake is reporting the <strong>standard error</strong> when trying to describe how spread out individual values are.</p>
<blockquote class="blockquote">
<p>❌ <em>“The average score was 80 ± 2 (SE)”</em><br>
✅ <em>“The average score was 80 ± 2 (SD)”</em></p>
</blockquote>
<p>In descriptive statistics—such as reporting the results of a survey, an experiment, or a class performance—you almost always want to use the <strong>standard deviation</strong>, because it reflects <strong>individual variability</strong>.</p>
<blockquote class="blockquote">
<p>📌 The standard error, by contrast, only makes sense if your goal is to communicate <strong>how uncertain your estimate of the mean is</strong>, not how diverse the sample is.</p>
</blockquote>
<hr>
</section>
<section id="mistake-2-adding-error-bars-to-a-barplot-without-clarifying-whether-its-sd-or-se" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="mistake-2-adding-error-bars-to-a-barplot-without-clarifying-whether-its-sd-or-se"><span class="header-section-number">4.2</span> Mistake 2: Adding Error Bars to a Barplot Without Clarifying Whether It’s SD or SE</h3>
<p>Barplots with error bars are everywhere—but often, those bars are unlabeled, or worse, mislabeled.</p>
<ul>
<li>If the error bars are <strong>standard deviation</strong>, they show the <strong>range of variation</strong> in the data.</li>
<li>If they are <strong>standard error</strong>, they show the <strong>precision of the mean estimate</strong>.</li>
</ul>
<p>Yet many charts leave this ambiguous or assume the reader will infer it.</p>
<blockquote class="blockquote">
<p>✏️ <strong>Always label your error bars.</strong> In R and ggplot2, you can add <code>labs(caption = "Error bars represent ±1 SE")</code> to avoid confusion.</p>
</blockquote>
<hr>
</section>
<section id="mistake-3-believing-that-se-can-describe-the-samples-spread" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="mistake-3-believing-that-se-can-describe-the-samples-spread"><span class="header-section-number">4.3</span> Mistake 3: Believing That SE Can Describe the Sample’s Spread</h3>
<p>Another subtle misinterpretation is thinking that <strong>a small SE implies the data itself is tightly clustered</strong>. But SE has nothing to do with spread among individual values.</p>
<blockquote class="blockquote">
<p>A sample can have high variability (large SD), but still have a small SE if the sample size is large.</p>
</blockquote>
<p>This is especially misleading in <strong>clinical trials</strong> or <strong>public health studies</strong>, where the sample size might be very large—but individual responses vary wildly.</p>
<blockquote class="blockquote">
<p>📉 Low SE ≠ Low diversity. It just means you’re confident about the average.</p>
</blockquote>
<hr>
</section>
<section id="mistake-4-reporting-se-without-context" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="mistake-4-reporting-se-without-context"><span class="header-section-number">4.4</span> Mistake 4: Reporting SE Without Context</h3>
<p>It’s not uncommon to see a mean value with a standard error reported like this:</p>
<blockquote class="blockquote">
<p><em>“Mean blood pressure: 132 ± 1.5”</em></p>
</blockquote>
<p>This may seem informative—but <strong>without knowing the sample size</strong>, this value has limited meaning.</p>
<p>Why? Because SE is <strong>dependent on</strong> <span class="math inline">\(n\)</span>. A standard error of 1.5 from 10 observations is very different from the same SE based on 10,000 observations.</p>
<blockquote class="blockquote">
<p>✔️ Always include the <strong>sample size</strong> and preferably also the <strong>standard deviation</strong>, especially if the goal is transparency and reproducibility.</p>
</blockquote>
<hr>
</section>
<section id="final-rule-of-thumb" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="final-rule-of-thumb"><span class="header-section-number">4.5</span> Final Rule of Thumb</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>If you want to…</th>
<th>Use…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Describe how individuals vary</td>
<td>Standard Deviation</td>
</tr>
<tr class="even">
<td>Quantify uncertainty about the sample mean</td>
<td>Standard Error</td>
</tr>
<tr class="odd">
<td>Construct a confidence interval</td>
<td>Standard Error</td>
</tr>
<tr class="even">
<td>Show variability in raw data</td>
<td>Standard Deviation</td>
</tr>
</tbody>
</table>
<p>By respecting the purpose and proper use of these two measures, you’ll avoid misleading your audience—and build more trust in your analyses.</p>
</section>
</section>
<section id="a-real-world-example-monthly-spending-survey-in-usd" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="a-real-world-example-monthly-spending-survey-in-usd"><span class="header-section-number">5</span> A Real-World Example: Monthly Spending Survey in USD</h2>
<p>Let’s now apply what we’ve learned in a more realistic, international scenario.</p>
<p>Imagine a survey conducted in a mid-sized city where 40 individuals are asked:</p>
<blockquote class="blockquote">
<p><em>“How much money do you spend per month (in US Dollars)?”</em></p>
</blockquote>
<p>We simulate responses centered around $2,000, with a standard deviation of $500.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">40</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>monthly_spending <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">2000</span>, <span class="at">sd =</span> <span class="dv">500</span>), <span class="dv">0</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(monthly_spending)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1720 1885 2779 2035 2065 2858</code></pre>
</div>
</div>
<section id="descriptive-statistics" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="descriptive-statistics"><span class="header-section-number">5.1</span> Descriptive Statistics</h3>
<p>Now let’s compute the mean, standard deviation, and standard error:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mean_spending <span class="ot">&lt;-</span> <span class="fu">mean</span>(monthly_spending)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>sd_spending <span class="ot">&lt;-</span> <span class="fu">sd</span>(monthly_spending)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>se_spending <span class="ot">&lt;-</span> sd_spending <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>mean_spending</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2022.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>sd_spending</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 448.8549</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>se_spending</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 70.9702</code></pre>
</div>
</div>
<p>Let’s interpret the output:</p>
<ul>
<li><p><strong>Mean monthly spending</strong>: approximately 2023 USD</p></li>
<li><p><strong>Standard deviation</strong>: approximately 449 USD</p></li>
<li><p><strong>Standard error</strong>: approximately 71 USD</p></li>
</ul>
</section>
<section id="what-do-these-numbers-tell-us" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="what-do-these-numbers-tell-us"><span class="header-section-number">5.2</span> What Do These Numbers Tell Us?</h3>
<ul>
<li><p>The <strong>standard deviation</strong> tells us that individual spending varies by about 449 USD from the average. So one person may spend only around 1574 USD, while another spends over 2471 USD.</p></li>
<li><p>The <strong>standard error</strong> tells us that the <strong>average</strong> we see in this sample could fluctuate by about ±71 USD due to sampling variability.</p></li>
</ul>
<div>
<p>📌 While individuals differ significantly in spending habits, the sample mean is relatively stable thanks to a sufficient sample size <span class="math inline">\(n =\)</span> 40</p>
</div>
</section>
<section id="visualizing-the-distribution" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="visualizing-the-distribution"><span class="header-section-number">5.3</span> Visualizing the Distribution</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">spending =</span> monthly_spending), <span class="fu">aes</span>(<span class="at">x =</span> spending)) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..), <span class="at">binwidth =</span> <span class="dv">250</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"darkblue"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> mean_spending), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of Monthly Spending"</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Monthly Spending (USD)"</span>, <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This graph shows:</p>
<ul>
<li><p>The <strong>red dashed line</strong> is the sample mean 2023 USD</p></li>
<li><p>The <strong>width</strong> of the histogram and smooth curve represents the variability in spending.</p></li>
<li><p>This is captured by the <strong>standard deviation</strong>, not the standard error.</p></li>
</ul>
</section>
<section id="confidence-interval-for-the-mean" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="confidence-interval-for-the-mean"><span class="header-section-number">5.4</span> Confidence Interval for the Mean</h3>
<p>Let’s calculate a 95% confidence interval using the standard error:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lower <span class="ot">&lt;-</span> mean_spending <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se_spending</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>upper <span class="ot">&lt;-</span> mean_spending <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se_spending</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(lower, upper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1883.498 2161.702</code></pre>
</div>
</div>
<p>Result:</p>
<blockquote class="blockquote">
<p><strong>Confidence interval:</strong> approximately 1883 to 2162 USD</p>
</blockquote>
<p>This tells us:</p>
<blockquote class="blockquote">
<p>“We are 95% confident that the true average monthly spending of the population lies between 1883 and 2162 USD.”</p>
</blockquote>
<p><strong>Remember:</strong> this range reflects <strong>uncertainty about the mean</strong>, not individual variability.</p>
</section>
</section>
<section id="conclusion" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">6</span> Conclusion</h2>
<p>Standard deviation and standard error are often mentioned in the same breath, but they serve <strong>very different purposes</strong> in data analysis and statistical reasoning.</p>
<ul>
<li><strong>Standard deviation</strong> reflects the <strong>natural variability</strong> in a dataset. It tells us how different individuals are from one another.</li>
<li><strong>Standard error</strong> quantifies the <strong>precision of a sample estimate</strong>, such as the mean. It tells us how much we can trust our estimate of the population parameter.</li>
</ul>
<p>While they are mathematically related, confusing one for the other can lead to serious misinterpretations—especially in scientific communication, data journalism, or policymaking.</p>
<p>Here are some final takeaways:</p>
<ul>
<li>Use <strong>standard deviation</strong> when describing the data you have.</li>
<li>Use <strong>standard error</strong> when making inferences about the population from your sample.</li>
<li>Always <strong>label your charts and error bars clearly</strong>, and <strong>report sample size</strong> to give proper context.</li>
<li>Don’t mistake low standard error for low variability—it only means your estimate is more precise, not that your data is more uniform.</li>
</ul>
<blockquote class="blockquote">
<p>🎯 In short:<br>
<strong>Standard deviation tells you about your data.</strong><br>
<strong>Standard error tells you how much you can trust your mean.</strong></p>
</blockquote>
<p>Understanding this distinction is more than just a statistical nuance—it’s a sign of analytical maturity.</p>
</section>
<section id="references" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="references"><span class="header-section-number">7</span> References</h2>
<ul>
<li><p>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2021). <em>An Introduction to Statistical Learning with Applications in R</em>. Springer. <a href="https://www.statlearning.com" class="uri">https://www.statlearning.com</a></p></li>
<li><p>Moore, D. S., McCabe, G. P., &amp; Craig, B. A. (2017). <em>Introduction to the Practice of Statistics</em>. W.H. Freeman.</p></li>
<li><p>R Core Team. (2024). <em>R: A language and environment for statistical computing</em>. R Foundation for Statistical Computing. <a href="https://www.r-project.org" class="uri">https://www.r-project.org</a></p></li>
<li><p>Wickham, H., Çetinkaya-Rundel, M., &amp; Grolemund, G. (2023). <em>R for Data Science (2e)</em>. <a href="https://r4ds.hadley.nz" class="uri">https://r4ds.hadley.nz</a></p></li>
<li><p>Navarro, D. (2019). <em>Learning Statistics with R: A tutorial for psychology students and other beginners</em>. <a href="https://learningstatisticswithr.com" class="uri">https://learningstatisticswithr.com</a></p></li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/mfatihtuzen\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="MFatihTuzen/blogComments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb18" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Standard Deviation vs. Standard Error: Meaning, Misuse, and the Math Behind the Confusion"</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> M. Fatih Tüzen</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [R, Statistics, Data Analysis, Standard Deviation, Standard Error]</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span><span class="co"> </span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 2</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="co">    code-overflow: scroll</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co">    code-block-background: true</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="al">![The left side illustrates standard deviation as the spread of individual data values around the population mean (μ). The right side shows standard error as the variability in sample means (x̄) obtained from repeated sampling. Notice how the SE distribution is narrower—it represents uncertainty in the estimate, not variability in the raw data.](sd_vs_se.png)</span>{fig-align="center" width="80%"}</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction: Why This Confusion Still Matters</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>In the world of data analysis and statistics, **standard deviation (SD)** and **standard error (SE)** are two concepts that are often misunderstood or—worse—used interchangeably. This confusion isn't just academic: misinterpreting these two measures can lead to poor conclusions, misleading visualizations, and incorrect inferences, especially in reports intended for non-technical audiences.</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>Think about this: you read a news article stating that *“the average income of a sample group is \$3,000 with a standard error of \$500.”* But then another article says *“the same average income with a standard deviation of \$500.”* Should your level of confidence change? Absolutely—because they tell two fundamentally different stories.</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>This article aims to:</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Define and differentiate standard deviation and standard error,</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Explore their mathematical foundations,</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Demonstrate their practical implications with real R code and visuals,</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Warn about common pitfalls and interpretation mistakes.</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>By the end of this post, you’ll not only **understand the difference** but also **know exactly when and why each metric matters**.</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a><span class="fu">## Definitions and Mathematical Foundation</span></span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a>Understanding the difference between **standard deviation** and **standard error** requires going beyond surface-level definitions. While they are mathematically related, they answer fundamentally different questions.</span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a><span class="fu">### Standard Deviation (SD)</span></span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a>Standard deviation is a measure of **variability** or **dispersion** within a single dataset. It tells us how far individual observations tend to deviate from the sample (or population) mean.</span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a>Mathematically, for a sample of size $n$, the sample standard deviation is given by:</span>
<span id="cb18-45"><a href="#cb18-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-46"><a href="#cb18-46" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb18-47"><a href="#cb18-47" aria-hidden="true" tabindex="-1"></a>s = \sqrt{ \frac{1}{n - 1} \sum_{i=1}^{n} (x_i - \bar{x})^2 }</span>
<span id="cb18-48"><a href="#cb18-48" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb18-49"><a href="#cb18-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-50"><a href="#cb18-50" aria-hidden="true" tabindex="-1"></a>Where:</span>
<span id="cb18-51"><a href="#cb18-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-52"><a href="#cb18-52" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$x_i$: Each data point</span>
<span id="cb18-53"><a href="#cb18-53" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\bar{x}$: Sample mean</span>
<span id="cb18-54"><a href="#cb18-54" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$n$: Number of observations</span>
<span id="cb18-55"><a href="#cb18-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-56"><a href="#cb18-56" aria-hidden="true" tabindex="-1"></a>Standard deviation is widely used in descriptive statistics to understand how **spread out** the values in a dataset are. A large SD implies high variability, while a small SD suggests the values are clustered closely around the mean.</span>
<span id="cb18-57"><a href="#cb18-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-58"><a href="#cb18-58" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; 📌 **Use case**: “How much do individual students’ test scores vary from the class average?”</span></span>
<span id="cb18-59"><a href="#cb18-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-60"><a href="#cb18-60" aria-hidden="true" tabindex="-1"></a><span class="fu">### Standard Error (SE)</span></span>
<span id="cb18-61"><a href="#cb18-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-62"><a href="#cb18-62" aria-hidden="true" tabindex="-1"></a>Standard error, in contrast, is a measure of **precision**—specifically, the precision of an estimate like the sample mean. It tells us how much the **sample mean** would vary if we repeatedly drew samples from the population.</span>
<span id="cb18-63"><a href="#cb18-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-64"><a href="#cb18-64" aria-hidden="true" tabindex="-1"></a>It is defined as:</span>
<span id="cb18-65"><a href="#cb18-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-66"><a href="#cb18-66" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb18-67"><a href="#cb18-67" aria-hidden="true" tabindex="-1"></a>\text{SE} = \frac{s}{\sqrt{n}}</span>
<span id="cb18-68"><a href="#cb18-68" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb18-69"><a href="#cb18-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-70"><a href="#cb18-70" aria-hidden="true" tabindex="-1"></a>As you can see, SE is directly related to the standard deviation but scaled down by the square root of the sample size. This reflects the idea that **more data gives more precise estimates**.</span>
<span id="cb18-71"><a href="#cb18-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-72"><a href="#cb18-72" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; 📌 **Use case**: “How much uncertainty is there in the sample mean as an estimate of the population mean?”</span></span>
<span id="cb18-73"><a href="#cb18-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-74"><a href="#cb18-74" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb18-75"><a href="#cb18-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-76"><a href="#cb18-76" aria-hidden="true" tabindex="-1"></a>In short:</span>
<span id="cb18-77"><a href="#cb18-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-78"><a href="#cb18-78" aria-hidden="true" tabindex="-1"></a>| Concept            | Measures                         | Based on                | Affected by Sample Size |</span>
<span id="cb18-79"><a href="#cb18-79" aria-hidden="true" tabindex="-1"></a>|------------------|------------------|------------------|-------------------|</span>
<span id="cb18-80"><a href="#cb18-80" aria-hidden="true" tabindex="-1"></a>| Standard Deviation | Spread of individual data points | Individual observations | ❌ No                   |</span>
<span id="cb18-81"><a href="#cb18-81" aria-hidden="true" tabindex="-1"></a>| Standard Error     | Uncertainty in the sample mean   | Sampling distribution   | ✅ Yes                  |</span>
<span id="cb18-82"><a href="#cb18-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-83"><a href="#cb18-83" aria-hidden="true" tabindex="-1"></a>Understanding this distinction is critical for drawing correct conclusions—especially in inferential statistics, confidence intervals, and hypothesis testing.</span>
<span id="cb18-84"><a href="#cb18-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-85"><a href="#cb18-85" aria-hidden="true" tabindex="-1"></a><span class="fu">## Visualizing the Difference with R: Simulation and Interpretation</span></span>
<span id="cb18-86"><a href="#cb18-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-87"><a href="#cb18-87" aria-hidden="true" tabindex="-1"></a>Let’s use R to **visualize** and **truly understand** the difference between standard deviation and standard error.</span>
<span id="cb18-88"><a href="#cb18-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-89"><a href="#cb18-89" aria-hidden="true" tabindex="-1"></a>We’ll start by generating a single random sample from a known population and examining the spread of individual values. Then, we’ll simulate multiple samples to show how the sample means vary—and how that variation reflects the standard error.</span>
<span id="cb18-90"><a href="#cb18-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-91"><a href="#cb18-91" aria-hidden="true" tabindex="-1"></a><span class="fu">### Standard Deviation: Spread of Values Within a Sample</span></span>
<span id="cb18-92"><a href="#cb18-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-95"><a href="#cb18-95" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-96"><a href="#cb18-96" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb18-97"><a href="#cb18-97" aria-hidden="true" tabindex="-1"></a>sample_data <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>)</span>
<span id="cb18-98"><a href="#cb18-98" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-99"><a href="#cb18-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-100"><a href="#cb18-100" aria-hidden="true" tabindex="-1"></a>We generate 50 values from a normal distribution with a mean of 100 and a standard deviation of 15. This mimics a situation like measuring the heights, weights, or incomes of 50 individuals.</span>
<span id="cb18-101"><a href="#cb18-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-102"><a href="#cb18-102" aria-hidden="true" tabindex="-1"></a>Let’s visualize how these values are distributed.</span>
<span id="cb18-103"><a href="#cb18-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-106"><a href="#cb18-106" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-107"><a href="#cb18-107" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb18-108"><a href="#cb18-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-109"><a href="#cb18-109" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> sample_data), <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb18-110"><a href="#cb18-110" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..), <span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb18-111"><a href="#cb18-111" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>) <span class="sc">+</span></span>
<span id="cb18-112"><a href="#cb18-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(x)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb18-113"><a href="#cb18-113" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-114"><a href="#cb18-114" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Standard Deviation: Spread of Individual Values"</span>,</span>
<span id="cb18-115"><a href="#cb18-115" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb18-116"><a href="#cb18-116" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-117"><a href="#cb18-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-118"><a href="#cb18-118" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-119"><a href="#cb18-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-120"><a href="#cb18-120" aria-hidden="true" tabindex="-1"></a>**What This Graph Shows**</span>
<span id="cb18-121"><a href="#cb18-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-122"><a href="#cb18-122" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The histogram shows the **distribution of raw data** from our single sample.</span>
<span id="cb18-123"><a href="#cb18-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-124"><a href="#cb18-124" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The black curve is a **kernel density estimate**, giving us a smooth representation of the distribution.</span>
<span id="cb18-125"><a href="#cb18-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-126"><a href="#cb18-126" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The red dashed line marks the **sample mean**.</span>
<span id="cb18-127"><a href="#cb18-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-128"><a href="#cb18-128" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The **spread around this mean**—the “thickness” of the histogram—is what the **standard deviation** quantifies.</span>
<span id="cb18-129"><a href="#cb18-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-130"><a href="#cb18-130" aria-hidden="true" tabindex="-1"></a>So, in simple terms: **standard deviation tells us how much individual values differ from their mean in one sample**. It answers the question:</span>
<span id="cb18-131"><a href="#cb18-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-132"><a href="#cb18-132" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; “Are most values close to the average, or are they all over the place?”</span></span>
<span id="cb18-133"><a href="#cb18-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-134"><a href="#cb18-134" aria-hidden="true" tabindex="-1"></a><span class="fu">### Standard Error: Spread of Sample Means Across Repeated Samples</span></span>
<span id="cb18-135"><a href="#cb18-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-136"><a href="#cb18-136" aria-hidden="true" tabindex="-1"></a>Now let’s go one level deeper. Instead of looking at one sample, let’s imagine we repeatedly draw many samples from the same population, each of size 50, and record their means.</span>
<span id="cb18-137"><a href="#cb18-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-140"><a href="#cb18-140" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-141"><a href="#cb18-141" aria-hidden="true" tabindex="-1"></a>sample_means <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">mean</span>(<span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>)))</span>
<span id="cb18-142"><a href="#cb18-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-143"><a href="#cb18-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-144"><a href="#cb18-144" aria-hidden="true" tabindex="-1"></a>Let’s see how those means are distributed:</span>
<span id="cb18-145"><a href="#cb18-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-148"><a href="#cb18-148" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-149"><a href="#cb18-149" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">mean =</span> sample_means), <span class="fu">aes</span>(<span class="at">x =</span> mean)) <span class="sc">+</span></span>
<span id="cb18-150"><a href="#cb18-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..), <span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"darkorange"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb18-151"><a href="#cb18-151" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>) <span class="sc">+</span></span>
<span id="cb18-152"><a href="#cb18-152" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(mean)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb18-153"><a href="#cb18-153" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-154"><a href="#cb18-154" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Standard Error: Variability of Sample Means"</span>,</span>
<span id="cb18-155"><a href="#cb18-155" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Sample Mean"</span>, <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb18-156"><a href="#cb18-156" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-157"><a href="#cb18-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-158"><a href="#cb18-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-159"><a href="#cb18-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-160"><a href="#cb18-160" aria-hidden="true" tabindex="-1"></a>**What This Graph Shows**</span>
<span id="cb18-161"><a href="#cb18-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-162"><a href="#cb18-162" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Each bar in the histogram represents the **frequency of sample means** in a small range.</span>
<span id="cb18-163"><a href="#cb18-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-164"><a href="#cb18-164" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The curve again shows the **estimated density** of the sample means.</span>
<span id="cb18-165"><a href="#cb18-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-166"><a href="#cb18-166" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The red dashed line is the **grand mean** of all 1,000 sample means—it should be close to 100.</span>
<span id="cb18-167"><a href="#cb18-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-168"><a href="#cb18-168" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Unlike the previous graph, here we don’t see individual values but **mean values from many samples**.</span>
<span id="cb18-169"><a href="#cb18-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-170"><a href="#cb18-170" aria-hidden="true" tabindex="-1"></a>This distribution is known as the **sampling distribution of the sample mean**.</span>
<span id="cb18-171"><a href="#cb18-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-172"><a href="#cb18-172" aria-hidden="true" tabindex="-1"></a>And the **standard deviation of this distribution is the standard error**:</span>
<span id="cb18-173"><a href="#cb18-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-176"><a href="#cb18-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-177"><a href="#cb18-177" aria-hidden="true" tabindex="-1"></a>se_estimate <span class="ot">&lt;-</span> <span class="fu">sd</span>(sample_means)</span>
<span id="cb18-178"><a href="#cb18-178" aria-hidden="true" tabindex="-1"></a>se_estimate</span>
<span id="cb18-179"><a href="#cb18-179" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-180"><a href="#cb18-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-181"><a href="#cb18-181" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpretation: Two Types of Spread, Two Different Questions</span></span>
<span id="cb18-182"><a href="#cb18-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-183"><a href="#cb18-183" aria-hidden="true" tabindex="-1"></a>Let’s pause and reflect on what we've seen so far.</span>
<span id="cb18-184"><a href="#cb18-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-185"><a href="#cb18-185" aria-hidden="true" tabindex="-1"></a>Although **standard deviation** and **standard error** are both measures of “spread,” they describe very different things, answer different questions, and are used in different contexts.</span>
<span id="cb18-186"><a href="#cb18-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-187"><a href="#cb18-187" aria-hidden="true" tabindex="-1"></a>| Concept            | What it Measures                               | Based on...           | Changes with Sample Size ($n$) |</span>
<span id="cb18-188"><a href="#cb18-188" aria-hidden="true" tabindex="-1"></a>|----------------|-------------------------|----------------|----------------|</span>
<span id="cb18-189"><a href="#cb18-189" aria-hidden="true" tabindex="-1"></a>| Standard Deviation | Spread of individual data values               | Single sample         | ❌ No                          |</span>
<span id="cb18-190"><a href="#cb18-190" aria-hidden="true" tabindex="-1"></a>| Standard Error     | Spread of sample means across repeated samples | Sampling distribution | ✅ Yes                         |</span>
<span id="cb18-191"><a href="#cb18-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-192"><a href="#cb18-192" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb18-193"><a href="#cb18-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-194"><a href="#cb18-194" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Summary of Interpretation</span></span>
<span id="cb18-195"><a href="#cb18-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-196"><a href="#cb18-196" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Standard deviation (SD)** tells us:\</span>
<span id="cb18-197"><a href="#cb18-197" aria-hidden="true" tabindex="-1"></a>    <span class="sc">\&gt;</span> *“How much do individual values differ from the average within a sample?”*</span>
<span id="cb18-198"><a href="#cb18-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-199"><a href="#cb18-199" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Standard error (SE)** tells us:\</span>
<span id="cb18-200"><a href="#cb18-200" aria-hidden="true" tabindex="-1"></a>    <span class="sc">\&gt;</span> *“How much would the sample average vary if we repeated the sampling?”*</span>
<span id="cb18-201"><a href="#cb18-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-202"><a href="#cb18-202" aria-hidden="true" tabindex="-1"></a>In other words:</span>
<span id="cb18-203"><a href="#cb18-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-204"><a href="#cb18-204" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**SD measures natural variability** among individuals (or observations).</span>
<span id="cb18-205"><a href="#cb18-205" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**SE measures the statistical uncertainty** of an estimate, usually the sample mean.</span>
<span id="cb18-206"><a href="#cb18-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-207"><a href="#cb18-207" aria-hidden="true" tabindex="-1"></a>This difference is not just semantic—it has **critical consequences** for data interpretation:</span>
<span id="cb18-208"><a href="#cb18-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-209"><a href="#cb18-209" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>You use **SD** when describing the spread of your sample or population.</span>
<span id="cb18-210"><a href="#cb18-210" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>You use **SE** when making inferences, estimating confidence intervals, or assessing how trustworthy your sample statistic is.</span>
<span id="cb18-211"><a href="#cb18-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-212"><a href="#cb18-212" aria-hidden="true" tabindex="-1"></a><span class="fu">#### The Mathematical Connection</span></span>
<span id="cb18-213"><a href="#cb18-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-214"><a href="#cb18-214" aria-hidden="true" tabindex="-1"></a>As we saw earlier, the standard error is mathematically derived from the standard deviation:</span>
<span id="cb18-215"><a href="#cb18-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-216"><a href="#cb18-216" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb18-217"><a href="#cb18-217" aria-hidden="true" tabindex="-1"></a>\text{SE} = \frac{s}{\sqrt{n}}</span>
<span id="cb18-218"><a href="#cb18-218" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb18-219"><a href="#cb18-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-220"><a href="#cb18-220" aria-hidden="true" tabindex="-1"></a>This formula reveals a fundamental principle in statistics:</span>
<span id="cb18-221"><a href="#cb18-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-222"><a href="#cb18-222" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The more data you collect (larger $n$), the **more stable** your sample mean becomes.</span>
<span id="cb18-223"><a href="#cb18-223" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>However, the **variability within the sample** (standard deviation $s$) may remain roughly the same—because it depends on the population, not on how many observations you took.</span>
<span id="cb18-224"><a href="#cb18-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-225"><a href="#cb18-225" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; 🧠 **Key insight**:\</span></span>
<span id="cb18-226"><a href="#cb18-226" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Standard deviation reflects the reality of your data.**\</span></span>
<span id="cb18-227"><a href="#cb18-227" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Standard error reflects your uncertainty about the mean.**</span></span>
<span id="cb18-228"><a href="#cb18-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-229"><a href="#cb18-229" aria-hidden="true" tabindex="-1"></a><span class="fu">## Common Mistakes and Misinterpretations</span></span>
<span id="cb18-230"><a href="#cb18-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-231"><a href="#cb18-231" aria-hidden="true" tabindex="-1"></a>Despite their differences, standard deviation and standard error are frequently confused—even in academic papers, business reports, and media articles. Below are some of the most common mistakes and why they matter.</span>
<span id="cb18-232"><a href="#cb18-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-233"><a href="#cb18-233" aria-hidden="true" tabindex="-1"></a><span class="fu">### Mistake 1: Using Standard Error Instead of Standard Deviation in Descriptive Summaries</span></span>
<span id="cb18-234"><a href="#cb18-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-235"><a href="#cb18-235" aria-hidden="true" tabindex="-1"></a>A classic mistake is reporting the **standard error** when trying to describe how spread out individual values are.</span>
<span id="cb18-236"><a href="#cb18-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-237"><a href="#cb18-237" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; ❌ *“The average score was 80 ± 2 (SE)”*\</span></span>
<span id="cb18-238"><a href="#cb18-238" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; ✅ *“The average score was 80 ± 2 (SD)”*</span></span>
<span id="cb18-239"><a href="#cb18-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-240"><a href="#cb18-240" aria-hidden="true" tabindex="-1"></a>In descriptive statistics—such as reporting the results of a survey, an experiment, or a class performance—you almost always want to use the **standard deviation**, because it reflects **individual variability**.</span>
<span id="cb18-241"><a href="#cb18-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-242"><a href="#cb18-242" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; 📌 The standard error, by contrast, only makes sense if your goal is to communicate **how uncertain your estimate of the mean is**, not how diverse the sample is.</span></span>
<span id="cb18-243"><a href="#cb18-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-244"><a href="#cb18-244" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb18-245"><a href="#cb18-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-246"><a href="#cb18-246" aria-hidden="true" tabindex="-1"></a><span class="fu">### Mistake 2: Adding Error Bars to a Barplot Without Clarifying Whether It’s SD or SE</span></span>
<span id="cb18-247"><a href="#cb18-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-248"><a href="#cb18-248" aria-hidden="true" tabindex="-1"></a>Barplots with error bars are everywhere—but often, those bars are unlabeled, or worse, mislabeled.</span>
<span id="cb18-249"><a href="#cb18-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-250"><a href="#cb18-250" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If the error bars are **standard deviation**, they show the **range of variation** in the data.</span>
<span id="cb18-251"><a href="#cb18-251" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If they are **standard error**, they show the **precision of the mean estimate**.</span>
<span id="cb18-252"><a href="#cb18-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-253"><a href="#cb18-253" aria-hidden="true" tabindex="-1"></a>Yet many charts leave this ambiguous or assume the reader will infer it.</span>
<span id="cb18-254"><a href="#cb18-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-255"><a href="#cb18-255" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; ✏️ **Always label your error bars.** In R and ggplot2, you can add </span><span class="in">`labs(caption = "Error bars represent ±1 SE")`</span><span class="at"> to avoid confusion.</span></span>
<span id="cb18-256"><a href="#cb18-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-257"><a href="#cb18-257" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb18-258"><a href="#cb18-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-259"><a href="#cb18-259" aria-hidden="true" tabindex="-1"></a><span class="fu">### Mistake 3: Believing That SE Can Describe the Sample’s Spread</span></span>
<span id="cb18-260"><a href="#cb18-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-261"><a href="#cb18-261" aria-hidden="true" tabindex="-1"></a>Another subtle misinterpretation is thinking that **a small SE implies the data itself is tightly clustered**. But SE has nothing to do with spread among individual values.</span>
<span id="cb18-262"><a href="#cb18-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-263"><a href="#cb18-263" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; A sample can have high variability (large SD), but still have a small SE if the sample size is large.</span></span>
<span id="cb18-264"><a href="#cb18-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-265"><a href="#cb18-265" aria-hidden="true" tabindex="-1"></a>This is especially misleading in **clinical trials** or **public health studies**, where the sample size might be very large—but individual responses vary wildly.</span>
<span id="cb18-266"><a href="#cb18-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-267"><a href="#cb18-267" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; 📉 Low SE ≠ Low diversity. It just means you’re confident about the average.</span></span>
<span id="cb18-268"><a href="#cb18-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-269"><a href="#cb18-269" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb18-270"><a href="#cb18-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-271"><a href="#cb18-271" aria-hidden="true" tabindex="-1"></a><span class="fu">### Mistake 4: Reporting SE Without Context</span></span>
<span id="cb18-272"><a href="#cb18-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-273"><a href="#cb18-273" aria-hidden="true" tabindex="-1"></a>It’s not uncommon to see a mean value with a standard error reported like this:</span>
<span id="cb18-274"><a href="#cb18-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-275"><a href="#cb18-275" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; *“Mean blood pressure: 132 ± 1.5”*</span></span>
<span id="cb18-276"><a href="#cb18-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-277"><a href="#cb18-277" aria-hidden="true" tabindex="-1"></a>This may seem informative—but **without knowing the sample size**, this value has limited meaning.</span>
<span id="cb18-278"><a href="#cb18-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-279"><a href="#cb18-279" aria-hidden="true" tabindex="-1"></a>Why? Because SE is **dependent on** $n$. A standard error of 1.5 from 10 observations is very different from the same SE based on 10,000 observations.</span>
<span id="cb18-280"><a href="#cb18-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-281"><a href="#cb18-281" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; ✔️ Always include the **sample size** and preferably also the **standard deviation**, especially if the goal is transparency and reproducibility.</span></span>
<span id="cb18-282"><a href="#cb18-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-283"><a href="#cb18-283" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb18-284"><a href="#cb18-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-285"><a href="#cb18-285" aria-hidden="true" tabindex="-1"></a><span class="fu">### Final Rule of Thumb</span></span>
<span id="cb18-286"><a href="#cb18-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-287"><a href="#cb18-287" aria-hidden="true" tabindex="-1"></a>| If you want to...                          | Use...             |</span>
<span id="cb18-288"><a href="#cb18-288" aria-hidden="true" tabindex="-1"></a>|--------------------------------------------|--------------------|</span>
<span id="cb18-289"><a href="#cb18-289" aria-hidden="true" tabindex="-1"></a>| Describe how individuals vary              | Standard Deviation |</span>
<span id="cb18-290"><a href="#cb18-290" aria-hidden="true" tabindex="-1"></a>| Quantify uncertainty about the sample mean | Standard Error     |</span>
<span id="cb18-291"><a href="#cb18-291" aria-hidden="true" tabindex="-1"></a>| Construct a confidence interval            | Standard Error     |</span>
<span id="cb18-292"><a href="#cb18-292" aria-hidden="true" tabindex="-1"></a>| Show variability in raw data               | Standard Deviation |</span>
<span id="cb18-293"><a href="#cb18-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-294"><a href="#cb18-294" aria-hidden="true" tabindex="-1"></a>By respecting the purpose and proper use of these two measures, you’ll avoid misleading your audience—and build more trust in your analyses.</span>
<span id="cb18-295"><a href="#cb18-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-296"><a href="#cb18-296" aria-hidden="true" tabindex="-1"></a><span class="fu">## A Real-World Example: Monthly Spending Survey in USD</span></span>
<span id="cb18-297"><a href="#cb18-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-298"><a href="#cb18-298" aria-hidden="true" tabindex="-1"></a>Let’s now apply what we’ve learned in a more realistic, international scenario.</span>
<span id="cb18-299"><a href="#cb18-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-300"><a href="#cb18-300" aria-hidden="true" tabindex="-1"></a>Imagine a survey conducted in a mid-sized city where 40 individuals are asked:</span>
<span id="cb18-301"><a href="#cb18-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-302"><a href="#cb18-302" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; *“How much money do you spend per month (in US Dollars)?”*</span></span>
<span id="cb18-303"><a href="#cb18-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-304"><a href="#cb18-304" aria-hidden="true" tabindex="-1"></a>We simulate responses centered around \$2,000, with a standard deviation of \$500.</span>
<span id="cb18-305"><a href="#cb18-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-308"><a href="#cb18-308" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-309"><a href="#cb18-309" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb18-310"><a href="#cb18-310" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">40</span></span>
<span id="cb18-311"><a href="#cb18-311" aria-hidden="true" tabindex="-1"></a>monthly_spending <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">2000</span>, <span class="at">sd =</span> <span class="dv">500</span>), <span class="dv">0</span>)</span>
<span id="cb18-312"><a href="#cb18-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-313"><a href="#cb18-313" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(monthly_spending)</span>
<span id="cb18-314"><a href="#cb18-314" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-315"><a href="#cb18-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-316"><a href="#cb18-316" aria-hidden="true" tabindex="-1"></a><span class="fu">### Descriptive Statistics</span></span>
<span id="cb18-317"><a href="#cb18-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-318"><a href="#cb18-318" aria-hidden="true" tabindex="-1"></a>Now let’s compute the mean, standard deviation, and standard error:</span>
<span id="cb18-319"><a href="#cb18-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-322"><a href="#cb18-322" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-323"><a href="#cb18-323" aria-hidden="true" tabindex="-1"></a>mean_spending <span class="ot">&lt;-</span> <span class="fu">mean</span>(monthly_spending)</span>
<span id="cb18-324"><a href="#cb18-324" aria-hidden="true" tabindex="-1"></a>sd_spending <span class="ot">&lt;-</span> <span class="fu">sd</span>(monthly_spending)</span>
<span id="cb18-325"><a href="#cb18-325" aria-hidden="true" tabindex="-1"></a>se_spending <span class="ot">&lt;-</span> sd_spending <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb18-326"><a href="#cb18-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-327"><a href="#cb18-327" aria-hidden="true" tabindex="-1"></a>mean_spending</span>
<span id="cb18-328"><a href="#cb18-328" aria-hidden="true" tabindex="-1"></a>sd_spending</span>
<span id="cb18-329"><a href="#cb18-329" aria-hidden="true" tabindex="-1"></a>se_spending</span>
<span id="cb18-330"><a href="#cb18-330" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-331"><a href="#cb18-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-332"><a href="#cb18-332" aria-hidden="true" tabindex="-1"></a>Let’s interpret the output:</span>
<span id="cb18-333"><a href="#cb18-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-334"><a href="#cb18-334" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Mean monthly spending**: approximately <span class="in">`r round(mean_spending, 0)`</span> USD</span>
<span id="cb18-335"><a href="#cb18-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-336"><a href="#cb18-336" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Standard deviation**: approximately <span class="in">`r round(sd_spending, 0)`</span> USD</span>
<span id="cb18-337"><a href="#cb18-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-338"><a href="#cb18-338" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Standard error**: approximately <span class="in">`r round(se_spending, 0)`</span> USD</span>
<span id="cb18-339"><a href="#cb18-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-340"><a href="#cb18-340" aria-hidden="true" tabindex="-1"></a><span class="fu">### What Do These Numbers Tell Us?</span></span>
<span id="cb18-341"><a href="#cb18-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-342"><a href="#cb18-342" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The **standard deviation** tells us that individual spending varies by about <span class="in">`r round(sd_spending, 0)`</span> USD from the average. So one person may spend only around <span class="in">`r round(mean_spending - sd_spending, 0)`</span> USD, while another spends over <span class="in">`r round(mean_spending + sd_spending, 0)`</span> USD.</span>
<span id="cb18-343"><a href="#cb18-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-344"><a href="#cb18-344" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The **standard error** tells us that the **average** we see in this sample could fluctuate by about ±<span class="in">`r round(se_spending, 0)`</span> USD due to sampling variability.</span>
<span id="cb18-345"><a href="#cb18-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-346"><a href="#cb18-346" aria-hidden="true" tabindex="-1"></a>&lt;div&gt;</span>
<span id="cb18-347"><a href="#cb18-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-348"><a href="#cb18-348" aria-hidden="true" tabindex="-1"></a>📌 While individuals differ significantly in spending habits, the sample mean is relatively stable thanks to a sufficient sample size $n =$ <span class="in">`r n`</span></span>
<span id="cb18-349"><a href="#cb18-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-350"><a href="#cb18-350" aria-hidden="true" tabindex="-1"></a>&lt;/div&gt;</span>
<span id="cb18-351"><a href="#cb18-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-352"><a href="#cb18-352" aria-hidden="true" tabindex="-1"></a><span class="fu">### Visualizing the Distribution</span></span>
<span id="cb18-353"><a href="#cb18-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-356"><a href="#cb18-356" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-357"><a href="#cb18-357" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb18-358"><a href="#cb18-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-359"><a href="#cb18-359" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">spending =</span> monthly_spending), <span class="fu">aes</span>(<span class="at">x =</span> spending)) <span class="sc">+</span></span>
<span id="cb18-360"><a href="#cb18-360" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..), <span class="at">binwidth =</span> <span class="dv">250</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb18-361"><a href="#cb18-361" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"darkblue"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb18-362"><a href="#cb18-362" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> mean_spending), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb18-363"><a href="#cb18-363" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-364"><a href="#cb18-364" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of Monthly Spending"</span>,</span>
<span id="cb18-365"><a href="#cb18-365" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Monthly Spending (USD)"</span>, <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb18-366"><a href="#cb18-366" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-367"><a href="#cb18-367" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-368"><a href="#cb18-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-369"><a href="#cb18-369" aria-hidden="true" tabindex="-1"></a>This graph shows:</span>
<span id="cb18-370"><a href="#cb18-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-371"><a href="#cb18-371" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The **red dashed line** is the sample mean <span class="in">`r round(mean_spending, 0)`</span> USD</span>
<span id="cb18-372"><a href="#cb18-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-373"><a href="#cb18-373" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The **width** of the histogram and smooth curve represents the variability in spending.</span>
<span id="cb18-374"><a href="#cb18-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-375"><a href="#cb18-375" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>This is captured by the **standard deviation**, not the standard error.</span>
<span id="cb18-376"><a href="#cb18-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-377"><a href="#cb18-377" aria-hidden="true" tabindex="-1"></a><span class="fu">### Confidence Interval for the Mean</span></span>
<span id="cb18-378"><a href="#cb18-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-379"><a href="#cb18-379" aria-hidden="true" tabindex="-1"></a>Let’s calculate a 95% confidence interval using the standard error:</span>
<span id="cb18-380"><a href="#cb18-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-383"><a href="#cb18-383" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-384"><a href="#cb18-384" aria-hidden="true" tabindex="-1"></a>lower <span class="ot">&lt;-</span> mean_spending <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se_spending</span>
<span id="cb18-385"><a href="#cb18-385" aria-hidden="true" tabindex="-1"></a>upper <span class="ot">&lt;-</span> mean_spending <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se_spending</span>
<span id="cb18-386"><a href="#cb18-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-387"><a href="#cb18-387" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(lower, upper)</span>
<span id="cb18-388"><a href="#cb18-388" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-389"><a href="#cb18-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-390"><a href="#cb18-390" aria-hidden="true" tabindex="-1"></a>Result:</span>
<span id="cb18-391"><a href="#cb18-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-392"><a href="#cb18-392" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Confidence interval:** approximately </span><span class="in">`r round(lower, 0)`</span><span class="at"> to </span><span class="in">`r round(upper, 0)`</span><span class="at"> USD</span></span>
<span id="cb18-393"><a href="#cb18-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-394"><a href="#cb18-394" aria-hidden="true" tabindex="-1"></a>This tells us:</span>
<span id="cb18-395"><a href="#cb18-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-396"><a href="#cb18-396" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; “We are 95% confident that the true average monthly spending of the population lies between </span><span class="in">`r round(lower, 0)`</span><span class="at"> and </span><span class="in">`r round(upper, 0)`</span><span class="at"> USD.”</span></span>
<span id="cb18-397"><a href="#cb18-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-398"><a href="#cb18-398" aria-hidden="true" tabindex="-1"></a>**Remember:** this range reflects **uncertainty about the mean**, not individual variability.</span>
<span id="cb18-399"><a href="#cb18-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-400"><a href="#cb18-400" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion</span></span>
<span id="cb18-401"><a href="#cb18-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-402"><a href="#cb18-402" aria-hidden="true" tabindex="-1"></a>Standard deviation and standard error are often mentioned in the same breath, but they serve **very different purposes** in data analysis and statistical reasoning.</span>
<span id="cb18-403"><a href="#cb18-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-404"><a href="#cb18-404" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Standard deviation** reflects the **natural variability** in a dataset. It tells us how different individuals are from one another.</span>
<span id="cb18-405"><a href="#cb18-405" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Standard error** quantifies the **precision of a sample estimate**, such as the mean. It tells us how much we can trust our estimate of the population parameter.</span>
<span id="cb18-406"><a href="#cb18-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-407"><a href="#cb18-407" aria-hidden="true" tabindex="-1"></a>While they are mathematically related, confusing one for the other can lead to serious misinterpretations—especially in scientific communication, data journalism, or policymaking.</span>
<span id="cb18-408"><a href="#cb18-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-409"><a href="#cb18-409" aria-hidden="true" tabindex="-1"></a>Here are some final takeaways:</span>
<span id="cb18-410"><a href="#cb18-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-411"><a href="#cb18-411" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Use **standard deviation** when describing the data you have.</span>
<span id="cb18-412"><a href="#cb18-412" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Use **standard error** when making inferences about the population from your sample.</span>
<span id="cb18-413"><a href="#cb18-413" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Always **label your charts and error bars clearly**, and **report sample size** to give proper context.</span>
<span id="cb18-414"><a href="#cb18-414" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Don’t mistake low standard error for low variability—it only means your estimate is more precise, not that your data is more uniform.</span>
<span id="cb18-415"><a href="#cb18-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-416"><a href="#cb18-416" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; 🎯 In short:\</span></span>
<span id="cb18-417"><a href="#cb18-417" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Standard deviation tells you about your data.**\</span></span>
<span id="cb18-418"><a href="#cb18-418" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Standard error tells you how much you can trust your mean.**</span></span>
<span id="cb18-419"><a href="#cb18-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-420"><a href="#cb18-420" aria-hidden="true" tabindex="-1"></a>Understanding this distinction is more than just a statistical nuance—it's a sign of analytical maturity.</span>
<span id="cb18-421"><a href="#cb18-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-422"><a href="#cb18-422" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
<span id="cb18-423"><a href="#cb18-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-424"><a href="#cb18-424" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2021). *An Introduction to Statistical Learning with Applications in R*. Springer. <span class="ot">&lt;https://www.statlearning.com&gt;</span></span>
<span id="cb18-425"><a href="#cb18-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-426"><a href="#cb18-426" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Moore, D. S., McCabe, G. P., &amp; Craig, B. A. (2017). *Introduction to the Practice of Statistics*. W.H. Freeman.</span>
<span id="cb18-427"><a href="#cb18-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-428"><a href="#cb18-428" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>R Core Team. (2024). *R: A language and environment for statistical computing*. R Foundation for Statistical Computing. <span class="ot">&lt;https://www.r-project.org&gt;</span></span>
<span id="cb18-429"><a href="#cb18-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-430"><a href="#cb18-430" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Wickham, H., Çetinkaya-Rundel, M., &amp; Grolemund, G. (2023). *R for Data Science (2e)*. <span class="ot">&lt;https://r4ds.hadley.nz&gt;</span></span>
<span id="cb18-431"><a href="#cb18-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-432"><a href="#cb18-432" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Navarro, D. (2019). *Learning Statistics with R: A tutorial for psychology students and other beginners*. <span class="ot">&lt;https://learningstatisticswithr.com&gt;</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2023, M. Fatih Tüzen</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This page is built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>